<?
// Set page title.
$this->headTitle ( $this->translate ( 'Search Home' ) );

// Init home's script
$this->headScript()->appendFile("init-home.js");

//Load home styles
 $this->headLink()->appendStylesheet('home.css');

// Disable top search box -- this page has a special layout.
$this->layout ()->searchbox = false;

// Set default value if necessary:
if (! isset ( $this->searchClassId )) {
	$this->searchClassId = 'Solr';
}

// Load search actions and settings (if any):
$options = $this->searchOptions ( $this->searchClassId );
$basicSearch = $options->getSearchAction ();
$advSearch = $options->getAdvancedSearchAction ();

$this->layout ()->breadcrumbs = false;
?>
<div class="searchHomeContent">
  <? if ($this->ils()->getOfflineMode() == "ils-offline"): ?>
    <div class="alert alert-warning">
		<h2><?=$this->transEsc('ils_offline_title')?></h2>
		<p>
			<strong><?=$this->transEsc('ils_offline_status')?></strong>
		</p>
		<p><?=$this->transEsc('ils_offline_home_message')?></p>
      <? $supportEmail = $this->escapeHtmlAttr($this->systemEmail()); ?>
      <p>
			<a href="mailto:<?=$supportEmail?>"><?=$supportEmail?></a>
		</p>
	</div>
  <? endif; ?>
  <div class="clearfix">
    <?=$this->render("search/searchboxhome.phtml")?>
  </div>
</div>

<div class="resources">
	<div class="container">
		<div class="row">
			<div id="wht-bwsr" class="col-md-8">
				<h3>¿Qué es el buscador regional?</h3>
				<p>
					Gracias a acuerdos técnicos y organizativos, LA Referencia ha ido integrando progresivamente los nodos nacionales de los países que la conforman, a una plataforma que cuenta con los estándares internacionales de interoperabilidad. Integra tanto artículos científicos provenientes de casi un centenar de universidades de América Latina, como material de interés de investigaciones académicas reflejadas en tesis doctorales y de maestría, en una amplia variedad de opciones temáticas.
				</p>
			</div>
			<div id="explr-cat" class="col-md-4 btn-resources">
				<a href="#" class="btn-u"><i class="search fa fa-folder-open search-btn"></i>
					Explorar catálogo</a>
			</div>
		</div>
	</div>
</div>

<div class="container content">
	<div class="row margin-bottom-30">
		<?=$this->render("servicies.phtml")?>
	</div>

	<div class="headline">
		<h2>Noticias recientes</h2>
	</div>
	<div class="row margin-bottom-20">
		<?=$this->render("news.phtml")?>
	</div>
	
	<div class="partners">
		<div class="headline">
			<h2>Nuestros socios</h2>
		</div>
		<div class="row">
			<?=$this->render("partners.phtml")?>
		</div>
	</div>
</div>