


<?
// Set page title.
$this->headTitle ( $this->translate ( 'Search Home' ) );

// Init home's script
$this->headScript()->appendFile("init-home.js");
//Partner's and Node's slider
$this->headScript()->appendFile("vendor/infinite-carousel.js");

//Load home styles
 $this->headLink()->appendStylesheet('home.css');

// Disable top search box -- this page has a special layout.
$this->layout ()->searchbox = false;

// Set default value if necessary:
if (! isset ( $this->searchClassId )) {
	$this->searchClassId = 'Solr';
}

// Load search actions and settings (if any):
$options = $this->searchOptions ( $this->searchClassId );
$basicSearch = $options->getSearchAction ();
$advSearch = $options->getAdvancedSearchAction ();

$this->layout ()->breadcrumbs = false;
?>

<style>

div.dropdown:hover > ul.dropdown-menu {
    display: block;    
}

</style>

<div class="searchHomeContent">
  <? if ($this->ils()->getOfflineMode() == "ils-offline"): ?>
    <div class="alert alert-warning">
		<h2><?=$this->transEsc('ils_offline_title')?></h2>
		<p>
			<strong><?=$this->transEsc('ils_offline_status')?></strong>
		</p>
		<p><?=$this->transEsc('ils_offline_home_message')?></p>
      <? $supportEmail = $this->escapeHtmlAttr($this->systemEmail()); ?>
      <p>
			<a href="mailto:<?=$supportEmail?>"><?=$supportEmail?></a>
		</p>
	</div>
  <? endif; ?>
  <div class="clearfix">
    <?=$this->render("home/searchbox_". $this->layout()->userLang .".phtml")?>
  </div>
</div>

<div class="resources">
	<div class="container">
		<?=$this->render("home/reg-brws/reg-brws-".$this->layout()->userLang.".phtml")?>
	</div>
</div>
<div class="network-home">

	<div id="pick-ntwrk" class="dropdown">
        <div class="dropdown-toggle" data-toggle="dropdown">
			<span class="ntwrk-number">9</span>
			<span class="ntwrk-txt"><?=$this->transEsc("Nodos nacionales")?></span>        
		</div>
        <ul class="dropdown-menu">
            <li><a href="<?=$this->url('home')?>Search/Results?lookfor=network_acronym%3AAR">Argentina</a></li>
			<li><a href="<?=$this->url('home')?>Search/Results?lookfor=network_acronym%3ABR">Brasil</a></li>
			<li><a href="<?=$this->url('home')?>Search/Results?lookfor=network_acronym%3ACL">Chile</a></li>
			<li><a href="<?=$this->url('home')?>Search/Results?lookfor=network_acronym%3ACO">Colombia</a></li>
			<li><a href="<?=$this->url('home')?>Search/Results?lookfor=network_acronym%3AEC">Ecuador</a></li>
			<li><a href="<?=$this->url('home')?>Search/Results?lookfor=network_acronym%3ASV">El Salvador</a></li>
			<li><a href="<?=$this->url('home')?>Search/Results?lookfor=network_acronym%3AMX">México</a></li>
			<li><a href="<?=$this->url('home')?>Search/Results?lookfor=network_acronym%3APE">Perú</a></li>
			<li><a href="<?=$this->url('home')?>Search/Results?lookfor=network_acronym%3AVE">Venezuela</a></li>
        </ul>
        
    </div>
    	
	<div id="docs">
		<a href="<?=$this->url('home')?>Search/Results?lookfor=*%3A*" style="text-decoration:none;">	
			<span class="ntwrk-number">783 966</span>
			<span class="ntwrk-txt"><?=$this->transEsc('Documentos')?></span>
		</a>
	</div>
	
	<div id="mix">
		<table class="table">
			<tr>
				<td>
					<a href="<?=$this->url('home')?>Search/Results?lookfor=format%3Aarticle">
					<span>490 833</span>
					<span><?=$this->transEsc('Artículos')?></span>
					</a>
				</a>
				</td>
				<td>
					<a href="<?=$this->url('home')?>Search/Results?lookfor=format%3AdoctoralThesis">
					<span>88 599</span>
					<span><?=$this->transEsc('Tesis de Doctorado')?></span>
					</a>
				</td>
			</tr>
			<tr>
				<td>
				    <a href="<?=$this->url('home')?>Search/Results?lookfor=format%3Areport">    
					<span>1 686</span>
					<span><?=$this->transEsc('Reportes')?></span>
					</a>
				</td>
				<td>
					<a href="<?=$this->url('home')?>Search/Results?lookfor=format%3AmasterThesis">
					<span>202 798</span>
					<span><?=$this->transEsc('Tesis de Maestría')?></span>
					</a>
				</td>
			</tr>
		</table>
	</div>
</div>

<div class="container content">
	
	<!-- ?=$this->render("home/servicies/servicies-".$this->layout()->userLang.".phtml")? -->	


	<?=$this->render("home/news/news-".$this->layout()->userLang.".phtml")?>
	
	
	<div class="partners">
		<div class="headline">
			<h2><?=$this->transEsc('Nuestros socios')?></h2>
		</div>
		<div class="row">
			<?=$this->render("partners.phtml")?>
		</div>
	</div>
	
	<div class="pick-nodes">
		<div class="headline">
			<h2>
			<?=$this->transEsc('Nodos cosechados')?>			
			</h2>			
		</div>
		<div class="row">
			<?=$this->render("nodes.phtml")?>
		</div>
	</div>
</div>
