<?
// Set default value if necessary:
if (! isset ( $this->searchClassId )) {
	$this->searchClassId = 'Solr';
}

// Load search actions and settings (if any):
$options = $this->searchOptions ( $this->searchClassId );
$handlers = $this->searchbox ()->getHandlers ( $this->searchClassId, isset ( $this->searchIndex ) ? $this->searchIndex : null );
$handlerCount = count ( $handlers );
$basicSearch = $this->searchbox ()->combinedHandlersActive () ? 'combined-searchbox' : $options->getSearchAction ();
$searchHome = $options->getSearchHomeAction ();
$advSearch = $options->getAdvancedSearchAction ();
$lastSort = $options->getLastSort ();
$lastLimit = $options->getLastLimit ();
?>
<div class="col-md-6" id="search-legend">
	<div id="red">
		<h2>RED FEDERADA DE REPOSITORIOS INSTITUCIONALES &nbsp; <span>DE PUBLICACIONES CIENTÍFICAS</span></h2>
	</div>
	<div id="repo">
		<h3>Integramos el material de los repositorios &nbsp;<br><span>de nueve países de América Latina<span></h3>
	</div>
</div>
<div class="col-md-6">
	<div id="search-home">
		<img class="arrow" src="<?=$this->imageLink('arrow.png') ?>"><h1>BÚSQUEDA</h1>
		<form role="search" class="form-inline" method="get" action="<?=$this->url($basicSearch)?>" name="searchForm" id="searchForm" autocomplete="off">
			
			<div class="form-group padding-bottom-20">	
				<div class="col-md-8 no-padding">
					<input class="form-control search-query<? if($this->searchbox()->autocompleteEnabled($this->searchClassId)):?> autocomplete searcher:<?=$this->escapeHtmlAttr($this->searchClassId) ?><? endif ?>"
					id="searchForm_lookfor" type="text" name="lookfor"
					value="<?=$this->escapeHtmlAttr($this->lookfor)?>" />
				</div>	
				<div class="col-md-4 no-padding">	
				    <? if ($handlerCount > 1): ?>
				      <select class="form-control" id="searchForm_type" name="type"	data-native-menu="false">
				        <? foreach ($handlers as $handler): ?>
				          <option value="<?=$this->escapeHtmlAttr($handler['value'])?>"	<?=$handler['selected'] ? ' selected="selected"' : ''?>>
				            <?=$handler['indent'] ? '-- ' : ''?><?=$this->transEsc($handler['label'])?>
				          </option>
				        <? endforeach; ?>
				      </select>
				    <? elseif ($handlerCount == 1): ?>
				      <input type="hidden" name="type" value="<?=$this->escapeHtmlAttr($handlers[0]['value'])?>" />
				    <? endif; ?>
			    </div>			    
			 </div>
			 
			 <div class="form-group"> 
			 	 <? if ($advSearch): ?>
			      <a href="<?=$this->url($advSearch)?>" class="btn btn-link" id="advance-search"><i class="fa fa-search-plus"></i> <?=$this->transEsc("Advanced Search")?></a>
			    <? endif; ?>
			   	    
			    <button type="submit" class="btn btn-primary" id="submit-home">
					<i class="fa fa-search"></i> <?=$this->transEsc("Find")?>
				</button>	   
		    </div>
		    
		</form>
		
		<script type="text/javascript">$("#searchForm_lookfor").focus()</script>
		
	</div>
</div>

