<div class="row margin-bottom-30">
	<div class="col-md-4">
		<div class="service">
			<i class="fa fa-file-text service-icon"></i>
			<div class="desc">
				<h4>Información para gestores</h4>
				<p>Gracias a acuerdos técnicos y organizativos, LA Referencia ha ido integrando progresivamente los nodos nacionales de los países que la conforman, a una plataforma que cuenta.
				</p>
			</div>
		</div>
	</div>
	<div class="col-md-4">
		<div class="service">
			<i class="fa fa-bar-chart-o service-icon"></i>
			<div class="desc">
				<h4>Estadísticas</h4>
				<p>Gracias a acuerdos técnicos y organizativos, LA Referencia ha ido integrando progresivamente los nodos nacionales de los países que la conforman, a una plataforma que cuenta.</p>
			</div>
		</div>
	</div>
	<div class="col-md-4">
		<div class="service">
			<i class="fa fa-files-o service-icon"></i>			
			<div class="desc">
				<h4>Proyectos</h4>
				<p>Gracias a acuerdos técnicos y organizativos, LA Referencia ha ido integrando progresivamente los nodos nacionales de los países que la conforman, a una plataforma que cuenta.</p>
			</div>
		</div>
	</div>
</div>	