<?
    // Set page title.
    $this->headTitle($this->translate('Click Statistics'));
    
    $this->headLink()->appendStylesheet('vendor/morris.css');
    $this->headScript()->appendFile('vendor/morris/raphael.min.js');
    $this->headScript()->appendFile('vendor/morris/morris.min.js');
    
?>


<div class="<?=$this->layoutClass('widebody')?>">
  <h2><?=$this->transEsc('Statistics')?></h2>
  
   <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <i class="fa fa-bar-chart-o fa-fw"></i> Clicks seg&uacute;n repositorio
                            <div class="pull-right">
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                                        Actions
                                        <span class="caret"></span>
                                    </button>
                                    <ul class="dropdown-menu pull-right" role="menu">
                                        <li><a href="#">Action</a>
                                        </li>
                                        <li><a href="#">Another action</a>
                                        </li>
                                        <li><a href="#">Something else here</a>
                                        </li>
                                        <li class="divider"></li>
                                        <li><a href="#">Separated link</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div id="clicks-line-chart"></div>
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-8 -->
            </div>
            <!-- /.row -->
      
</div>


<script type="text/javascript">

var rawJson =  <?=json_encode($this->pivots) ?>;
var data = [];
var sources = {}

$.each( rawJson, function( key, value ) {
  var entry = {}
  entry['timestamp'] = key;

  $.each( value.pivot, function( i, pivot ) {
	entry[pivot.value] = pivot.count;
	sources[pivot.value] = "";
  });

  data.push(entry);
});

Morris.Line({
    element: 'clicks-line-chart',
    data: data,
    xkey: 'timestamp', 
	ykeys: sources.keys(),
	labels: sources.keys(),
    pointSize: 2,
    hideHover: 'auto',
    resize: true
});

</script>

<!--  div class="<?=$this->layoutClass('sidebar')?>">
  <?=$this->render("admin/menu.phtml")?>
</div-->
