<?
    // Set page title.
    $this->headTitle($this->translate('Click Statistics'));
    
    $this->headLink()->appendStylesheet('vendor/morris.css');
    $this->headScript()->appendFile('vendor/morris/raphael.min.js');
    $this->headScript()->appendFile('vendor/morris/morris.min.js');
    
?>

<table class="table table-striped">
<?=json_encode($this->pivots) ?>
 <? foreach($this->pivots[0]['pivot'] as $record): ?>
          <tr><td><?=serialize($record)?></td></tr>
<? endforeach; ?>

</table>



<div class="<?=$this->layoutClass('widebody')?>">
  <h2><?=$this->transEsc('Statistics')?></h2>
  
<? if(!empty($this->topRecords)): ?>
    <h3>Top Records<? if($this->recordsBySource): ?> by Source<? endif; ?></h3>
    <? if($this->recordsBySource): ?>
      <? foreach($this->topRecords as $source=>$records): ?>
        <span style="font-size:14px"><?=$source ?></span>
        <table class="table table-striped">
        <? foreach($records as $record): ?>
          <tr><td><?=$record['value'] ?></td><td><?=$record['count'] ?></td></tr>
        <? endforeach; ?>
        </table>
      <? endforeach; ?>
    <? else: ?>
      <table class="table table-striped">
        <? foreach($this->topRecords as $record): ?>
          <tr><td><?=$record['value'] ?></td><td><?=$record['count'] ?></td><td><?=$record['source'] ?></td></tr>
        <? endforeach; ?>
      </table>
    <? endif; ?>
  <? endif; ?>




  
   <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <i class="fa fa-bar-chart-o fa-fw"></i> Clicks seg&uacute;n repositorio
                            <div class="pull-right">
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                                        Actions
                                        <span class="caret"></span>
                                    </button>
                                    <ul class="dropdown-menu pull-right" role="menu">
                                        <li><a href="#">Action</a>
                                        </li>
                                        <li><a href="#">Another action</a>
                                        </li>
                                        <li><a href="#">Something else here</a>
                                        </li>
                                        <li class="divider"></li>
                                        <li><a href="#">Separated link</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div id="clicks-line-chart"></div>
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-8 -->
            </div>
            <!-- /.row -->
      
</div>

<script type="text/javascript">
<!--

//-->

Morris.Line({
    element: 'clicks-line-chart',
    data: [{
        period: '2010 Q1',
        iphone: 2666,
        ipad: 100,
        itouch: 2647
    }, {
        period: '2011 Q1',
        iphone: 2778,
        ipad: 2294,
        itouch: 2441
    }, {
        period: '2012 Q3',
        iphone: 4912,
        ipad: 1969,
        itouch: 2501
    },],
    xkey: 'period',
    ykeys: ['iphone', 'ipad', 'itouch'],
    labels: ['Argentina', 'Brasil', 'M&eacute;xico'],
    pointSize: 2,
    hideHover: 'auto',
    resize: true
});

</script>

<!--  div class="<?=$this->layoutClass('sidebar')?>">
  <?=$this->render("admin/menu.phtml")?>
</div-->
