

<div class="row"><br/></div>
   
<h2>¿Cómo lo hacemos?</h2>
	
<div class="row"><br/>
            
	<div class="col-lg-11">
    
	    <p>            
	    Para que los usuarios puedan tener acceso a texto completo al material académico que se encuentra en los repositorios institucionales de los nueve países miembros de LA Referencia, trabajamos previamente en procesos organizativos y técnicos que garantizan la calidad de los datos, centrándonos en varias fases:
		</p>
		
		<ul>
			<li><b>Acordamos:</b> los países miembros suscriben acuerdos regionales para definir políticas comunes y estándares de calidad con el objetivo de construir una red federada de repositorios de documentación científica.</li>
			<li><b>Cosechamos:</b> periódicamente recolectamos los registros de metadatos ofrecidos por los repositorios de la red, manteniendo actualizados los contenidos ofrecidos en el portal.</li>
			<li><b>Validamos:</b> generamos mecanismos para asegurar la calidad de la información publicada, de acuerdo a las directrices de calidad acordadas con los países miembros.</li>
			<li><b>Federamos:</b> realizamos un proceso de integración e indexación de los contenidos cosechados, facilitando a los usuarios, servicios de búsqueda con un acceso unificado.</li> 
			<li><b>Ofrecemos:</b> en el portal público de búsqueda, facilitamos la recuperación de la información y el acceso a los documentos en su repositorio institucional original, en un ambiente en constante mejora para desplegar estadísticas sobre los contenidos y su impacto. Un proveedor OAI-PMH unificado permite así la cosecha de los registros de la red, maximizando la visibilidad de la producción científica de la región.</li>
	    </ul>            
             
    </div>
</div>                
<!-- /.row -->