<div class="headline">
		<h2>Recent news</h2>
</div>
<div class="row margin-bottom-20">
	<div class="col-md-4 col-sm-12">
		<div class="thumbnails thumbnail-style thumbnail-kenburn">
			<div class="thumbnail-img col-md-12 col-sm-6">
				<div class="overflow-hidden">
					<img class="img-responsive" src="<?=$this->imageLink('news/noticia_1.jpg')?>" alt="" />
				</div>
				<a target="_blank" class="btn-more hover-effect" href="http://lareferencia.redclara.net/rfr/noticias/llego-la-web-semantica-la-referencia">+ <?=$this->transEsc("read more")?></a>
			</div>
			<div class="caption col-md-12 col-sm-6">
				<h3>
					<a target="_blank" class="hover-effect" href="http://lareferencia.redclara.net/rfr/noticias/llego-la-web-semantica-la-referencia">Noticia 1</a>
				</h3>
				<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus etiam sem...</p>
			</div>
		</div>
	</div>
	<div class="col-md-4 col-sm-12">
		<div class="thumbnails thumbnail-style thumbnail-kenburn ">
			<div class="thumbnail-img col-md-12 col-sm-6">
				<div class="overflow-hidden">
					<img class="img-responsive" src="<?=$this->imageLink('news/noticia_2.jpg')?>" alt=""/>
				</div>
				<a target="_blank" class="btn-more hover-effect" href="http://lareferencia.redclara.net/rfr/noticias/peru-lanza-nueva-version-de-nodo-nacional">+ <?=$this->transEsc("read more")?></a>
			</div>
			<div class="caption col-md-12 col-sm-6">
				<h3>
					<a target="_blank" class="hover-effect" href="http://lareferencia.redclara.net/rfr/noticias/peru-lanza-nueva-version-de-nodo-nacional">Noticia 2</a>
				</h3>
				<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus etiam sem...</p>
			</div>
		</div>
	</div>
	<div class="col-md-4 col-sm-12">
		<div class="thumbnails thumbnail-style thumbnail-kenburn ">
			<div class="thumbnail-img col-md-12 col-sm-6">
				<div class="overflow-hidden">
					<img class="img-responsive" src="<?=$this->imageLink('news/noticia_3.jpg')?>" alt="" />
				</div>
				<a target="_blank" class="btn-more hover-effect" href="http://lareferencia.redclara.net/rfr/noticias/argentina-apuntando-una-nueva-cultura-abierta-y-compartida">+ <?=$this->transEsc("read more")?></a>
			</div>
			<div class="caption col-md-12 col-sm-6">
				<h3>
					<a target="_blank" class="hover-effect" href="">Noticia 3</a>
				</h3>
				<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus etiam sem...</p>
			</div>
		</div>
	</div>
</div>