<ul class="nav navbar-nav">
    <!-- Home -->
    <li class=" active">
        <a href="<?=$this->url('home')?>">
            INICIO
        </a>
    </li>
    <!-- End Home -->

    <!-- Pages -->                        
    <li class="dropdown">
        <a href="<?=$this->url('home')?>Statistics/Map" class="dropdown-toggle" data-toggle="dropdown">
            REPOSITORIOS
        </a>
        <ul class="dropdown-menu">
            <!--li><a href="<?=$this->url('home')?>Statistics/Map">Mapa de la Red</a></li-->
            <li><a href="#">Instituciones cosechadas</a></li>
        </ul>
        
    </li>
    <!-- End Pages -->

    <!-- Features -->
    <li class="dropdown">
        <a href="<?=$this->url('home')?>Statistics/Networks" class="dropdown-toggle" data-toggle="dropdown">
            ESTADÍSTICAS
        </a>
        <ul class="dropdown-menu">
            <li><a href="<?=$this->url('home')?>Statistics/Count?field=format">Estadísticas de metadatos</a></li>
            <li><a href="<?=$this->url('home')?>Statistics/Clicks">Estadísticas de acceso</a></li>
            <li><a href="<?=$this->url('home')?>Statistics/Networks">Estadísticas de cosecha</a></li>
        </ul>
        
    </li>
    <!-- End Features -->

    <!-- Explorar -->
    <li>
        <a href="<?=$this->url('home')?>Browse/Home">
            EXPLORAR
        </a>                            
    </li>
    <!-- End Explorar -->

    <!-- Usuario -->
    <li class="dropdown">
        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
            USUARIO
        </a>
        <ul class="dropdown-menu">
            <li><a href="<?=$this->url('home')?>MyResearch/Home">Identificarse</a></li>
            <li><a href="<?=$this->url('home')?>MyResearch/Account">Registrarse como usuario</a></li>
            <li><a href="<?=$this->url('home')?>MyResearch/Recover">Recuperación de contraseña</a></li>
        </ul>
    </li>                    
    <!-- End Usuario -->
    
    <!-- Acerca de -->
    <li class="dropdown">
        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
            ACERCA DE
        </a>
        <ul class="dropdown-menu">
            <li><a href="<?=$this->url('home')?>Contents/Home?section=how">¿Cómo lo hacemos?</a></li>
            <li><a href="<?=$this->url('home')?>Contents/Home?section=who">¿Quiénes participan?</a></li>
        </ul>
    </li>                    
    <!-- End Acerca de -->
</ul>
