<div class="row">
	<div id="wht-bwsr" class="col-md-8">
		<h3>¿Qué es el buscador regional?</h3>
		<p>
Servicio que apoya las estrategias nacionales de Acceso Abierto en América Latina mediante una plataforma con estándares de interoperabilidad. A partir de nodos nacionales, se integran artículos científicos, tesis doctorales y de maestría, provenientes de más de un centenar de universidades e instituciones de investigación. Esta experiencia se basa en acuerdos técnicos y organizativos entre organismos públicos de ciencia y tecnología (Ministerios y Oncyts) de los países miembros, conjuntamente con RedCLARA.
				</p>
				<a href="http://lareferencia.redclara.net/">Conózcanos más</a>				
		
	</div>
	<div id="explr-cat" class="col-md-4 btn-resources">
		<!--a target="_blank" href="http://www.lareferencia.info/intelligo/" class="btn-u" style="width: 280px;">
			EXPLORAR MAPAS CONCEPTUALES
	    </a-->
	    <a target="_blank" href="http://lareferencia.redclara.net/rfr/" class="btn-u" style="width: 280px;">
			SITIO INSTITUCIONAL
	    </a>
	  
			
	</div>
</div>
