<div class="row">
	<div id="wht-bwsr" class="col-md-8">
		<h3>What is the regional search engine?</h3>
		<p>
Service supporting national strategies in Latin America Open Access via a platform interoperability standards. From national nodes, scientific articles, dissertations and master's degrees from more than a hundred universities and research institutions are integrated. This experience is based on technical and organizational arrangements between public science and technology organizations (ministries and ONCYTs) member countries, together with REDCLARA.				</p>
				<a href="http://lareferencia.redclara.net/">Learn more</a>				
				
	</div>
	<div id="explr-cat" class="col-md-4 btn-resources">
		<a target="_blank" href="http://www.lareferencia.info/intelligo/" class="btn-u">EXPLORE CONCEPT MAPS</a>
	</div>
</div>