<div class="row">
	<div id="wht-bwsr" class="col-md-8">
		<h3>Que é o motor de pesquisa regional?</h3>
		<p>
Serviço de apoio a estratégias nacionais na América Latina Open Access via uma plataforma de padrões de interoperabilidade. De nós nacionais, artigos científicos, dissertações e mestrados de mais de uma centena de universidades e instituições de pesquisa estão integrados. Esta experiência é baseada em disposições técnicas e organizacionais entre ciência e tecnologia organizações públicas (ministérios e ONCYTs) países-membros, juntamente com CLARA.						</p>
						
		<a href="http://lareferencia.redclara.net/">Saber mais</a>				
	</div>
	
	<div id="explr-cat" class="col-md-4 btn-resources">
			<a target="_blank" href="http://www.lareferencia.info/intelligo/" class="btn-u">
			MAPAS CONCEITUAIS</a>
			</div>
</div>