<div class="row">
	<div id="wht-bwsr" class="col-md-8">
		<h3>¿Qué es el buscador regional portugues?</h3>
		<p>
			Servicio basado en acuerdos técnicos y organizativos entre organismos públicos de ciencia y tecnología (Ministerios y Oncyts), junto a RedCLARA. Apoya las estrategias nacionales de acceso abierto mediante una plataforma con estándares de interoperabilidad. Integra vía nodos nacionales tanto artículos científicos, provenientes de casi un centenar de universidades e instituciones de investigación de América Latina, como material académico reflejado en tesis doctorales y de maestría. <br/><a target="_blank" href="http://lareferencia.redclara.net/rfr/">Leer más sobre LA Referencia </a> 
				</p>
	</div>
	<div id="explr-cat" class="col-md-4 btn-resources">
			<a target="_blank" href="http://www.lareferencia.info/intelligo/" class="btn-u">
			Explorar Intelligo </a>
			</div>
</div>