<div class="row">
	<div id="wht-bwsr" class="col-md-8">
		<h3>What is the regional search engine?</h3>
		<p>A service that supports national open access strategies in Latin America via a platform with interoperability standards. From national nodes, scientific articles, master and doctoral dissertations are harvested from repositories in universities and research institutions. This experience is based on technical and organizational agreements between public science and technology organizations (Ministries and ONCYTs ) with  RedCLARA.</p>
				<a href="http://lareferencia.redclara.net/">Learn more</a>				
				
	</div>
	<div id="explr-cat" class="col-md-4 btn-resources">
		<a target="_blank" href="http://www.lareferencia.info/intelligo/" class="btn-u" style="width: 280px;">
			EXPLORE CONCEPTUAL MAPS
	    </a>
	    <a target="_blank" href="http://lareferencia.redclara.net/rfr/" class="btn-u" style="width: 280px;">
			INSTITUTIONAL SITE
	    </a>
	  
			
	</div>
</div>