<? if ($mobileViewLink = $this->mobileUrl()): // display 'return to mobile' link when applicable ?>
  <hr/>
  <div class="mobileViewLink"><a href="<?=$this->escapeHtml($mobileViewLink)?>"><?=$this->transEsc("mobile_link")?></a></div>
<? endif; ?>

<hr/>

<div class="small">
   <br/><br/>
   <p>El Repositorio Nacional Digital de Ciencia, Tecnología e Innovación de Acceso Abierto denominado ALICIA (Acceso Libre a Información Científica para la Innovación), es administrado por el Consejo Nacional de Ciencia, Tecnología e Innovación Tecnológica (CONCYTEC) con el  propósito de conformar una red nacional interoperable de repositorios digitales, a partir del establecimiento de políticas, estándares y protocolos comunes a todos los integrantes de la Red.</p><p> </p><p> </p><p>Copyright © 2014 Consejo Nacional de Ciencia, Tecnología e Innovación Tecnológica<br /> Av. Del Aire N° 485 San Borja, Lima- Perú. Telf. 051-1-2251150</p>
</div>
