<div class="viewport" id="nodes-viewport">
	<ul class="sildes-list">
	<li>
	  <a target="_blank" href="http://repositoriosdigitales.mincyt.gob.ar/">
		<img src="<?=$this->imageLink('nodes/clara-bw.jpg')?>" alt=""> 
	    <img class="partner-color"  src="<?=$this->imageLink('nodes/clara.jpg')?>" alt=""/>
	  </a>
	</li>
	<li>
	  <a target="_blank" href="http://oasis.ibict.br/">
		<img src="<?=$this->imageLink('nodes/clara-bw.jpg')?>" alt=""> 
	    <img class="partner-color"  src="<?=$this->imageLink('nodes/clara.jpg')?>" alt=""/>
	  </a>
	</li>
	<li >
	  <a target="_blank" href="http://www.sic.informacioncientifica.cl/">
		<img src="<?=$this->imageLink('nodes/clara-bw.jpg')?>" alt=""> 
	    <img class="partner-color"  src="<?=$this->imageLink('nodes/clara.jpg')?>" alt=""/>
	  </a>
	</li>
	<li >
	  <a target="_blank" href="http://bdcol.org/">
		<img src="<?=$this->imageLink('nodes/clara-bw.jpg')?>" alt=""> 
	    <img class="partner-color"  src="<?=$this->imageLink('nodes/clara.jpg')?>" alt=""/>
	  </a>
	</li>
	<li >
	  <a target="_blank" href="http://repositorio.educacionsuperior.gob.ec/">
		<img src="<?=$this->imageLink('nodes/clara-bw.jpg')?>" alt=""> 
	    <img class="partner-color"  src="<?=$this->imageLink('nodes/clara.jpg')?>" alt=""/>
	  </a>
	</li>
	<li >
	  <a target="_blank" href="http://www.remeri.org.mx/portal/index.html">
		<img src="<?=$this->imageLink('nodes/clara-bw.jpg')?>" alt=""> 
	    <img class="partner-color"  src="<?=$this->imageLink('nodes/clara.jpg')?>" alt=""/>
	  </a>
	</li>
	<li >
	  <a target="_blank" href="http://alicia.concytec.gob.pe/alicia/">
		<img src="<?=$this->imageLink('nodes/clara-bw.jpg')?>" alt=""> 
	    <img class="partner-color"  src="<?=$this->imageLink('nodes/clara.jpg')?>" alt=""/>
	  </a>
	</li>
	<li >
	  <a target="_blank" href="http://www.redicces.org.sv/jspui/">
		<img src="<?=$this->imageLink('nodes/clara-bw.jpg')?>" alt=""> 
	    <img class="partner-color"  src="<?=$this->imageLink('nodes/clara.jpg')?>" alt=""/>
	  </a>
	</li>
	</ul>
</div>