<div class="viewport" id="partns-viewport">
	<ul class="sildes-list">
		<li>
			<a target="_blank" href="">
				<img src="<?=$this->imageLink('partners/clara-bw.jpg')?>" alt=""> 
			    <img class="partner-color"  src="<?=$this->imageLink('partners/clara.jpg')?>" alt=""/>
		  	</a>
		</li>
		<li>
			<a target="_blank" href="http://www.mincyt.gob.ar/">
				<img src="<?=$this->imageLink('partners/clara-bw.jpg')?>" alt=""> 
			    <img class="partner-color"  src="<?=$this->imageLink('partners/clara.jpg')?>" alt=""/>
		  	</a>
		</li>
		
		 
		<li>
			<a target="_blank" href="http://www.ibict.br/">
				<img src="<?=$this->imageLink('partners/clara-bw.jpg')?>" alt=""> 
			    <img class="partner-color"  src="<?=$this->imageLink('partners/clara.jpg')?>" alt=""/>
		  	</a>
		</li>
		<li>
			<a target="_blank" href="http://www.conicyt.cl/">
				<img src="<?=$this->imageLink('partners/clara-bw.jpg')?>" alt=""> 
			    <img class="partner-color"  src="<?=$this->imageLink('partners/clara.jpg')?>" alt=""/>
		  	</a>
		</li>
		<li>
			<a target="_blank" href="http://www.mineducacion.gov.co/">
				<img src="<?=$this->imageLink('partners/clara-bw.jpg')?>" alt=""> 
			    <img class="partner-color"  src="<?=$this->imageLink('partners/clara.jpg')?>" alt=""/>
		  	</a>
		</li>
		<li>
			<a target="_blank" href="http://www.colciencias.gov.co/">
				<img src="<?=$this->imageLink('partners/clara-bw.jpg')?>" alt=""> 
			    <img class="partner-color"  src="<?=$this->imageLink('partners/clara.jpg')?>" alt=""/>
		  	</a>
		</li>
		<li>
			<a target="_blank" href="http://www.educacionsuperior.gob.ec/">
				<img src="<?=$this->imageLink('partners/clara-bw.jpg')?>" alt=""> 
			    <img class="partner-color"  src="<?=$this->imageLink('partners/clara.jpg')?>" alt=""/>
		  	</a>
		</li>
		<li>
			<a target="_blank" href="http://www.conacyt.mx/">
				<img src="<?=$this->imageLink('partners/clara-bw.jpg')?>" alt=""> 
			    <img class="partner-color"  src="<?=$this->imageLink('partners/clara.jpg')?>" alt=""/>
		  	</a>
		</li>
		<li>
			<a target="_blank" href="http://portal.concytec.gob.pe/">
				<img src="<?=$this->imageLink('partners/clara-bw.jpg')?>" alt=""> 
			    <img class="partner-color"  src="<?=$this->imageLink('partners/clara.jpg')?>" alt=""/>
		  	</a>
		</li>
		<li>
			<a target="_blank" href="http://www.cienciaytecnologia.edu.sv/">
				<img src="<?=$this->imageLink('partners/clara-bw.jpg')?>" alt=""> 
			    <img class="partner-color"  src="<?=$this->imageLink('partners/clara.jpg')?>" alt=""/>
		  	</a>
		</li>
		<li>
			<a target="_blank" href="http://www3.reacciun.ve/">
				<img src="<?=$this->imageLink('partners/clara-bw.jpg')?>" alt=""> 
			    <img class="partner-color"  src="<?=$this->imageLink('partners/clara.jpg')?>" alt=""/>
		  	</a>
		</li>
	</ul>
</div>	