<ul class="nav navbar-nav">
    <!-- Home -->
    <li class=" active">
        <a href="<?=$this->url('home')?>">
            <?=$this->transEsc("INICIO")?>
        </a>
    </li>
    <!-- End Home -->

    <!-- Pages -->                        
    <li class="dropdown">
        <a href="<?=$this->url('home')?>Statistics/Map" class="dropdown-toggle" data-toggle="dropdown">
            <?=$this->transEsc("PAÍSES")?>        
        </a>
        <ul class="dropdown-menu">
            <li><a href="<?=$this->url('home')?>Statistics/Map"><?=$this->transEsc("Mapa de la Red")?> </a></li>
            <li><a href="<?=$this->url('home')?>Contents/Home?section=networks"><?=$this->transEsc("Nodos e Instituciones cosechadas")?> </a></li>
        </ul>
        
    </li>
    <!-- End Pages -->

    <!-- Features -->
    <li class="dropdown">
        <a href="<?=$this->url('home')?>Statistics/Networks" class="dropdown-toggle" data-toggle="dropdown">
            <?=$this->transEsc("ESTADÍSTICAS")?>        
        </a>
        <ul class="dropdown-menu">
            <li><a href="<?=$this->url('home')?>Statistics/Count?field=format"><?=$this->transEsc("Estadísticas de metadatos")?></a></li>
            <!--li><a href="<?=$this->url('home')?>Statistics/Clicks"><?=$this->transEsc("Estadísticas de acceso")?></a></li-->
            <li><a href="<?=$this->url('home')?>Statistics/Networks"><?=$this->transEsc("Estadísticas de cosecha")?></a></li>
        </ul>
        
    </li>
    <!-- End Features -->

    <!-- Explorar -->
    <li>
        <a href="<?=$this->url('home')?>Browse/Home">
            <?=$this->transEsc("EXPLORAR")?> 
        </a>                            
    </li>
    <!-- End Explorar -->

    <!-- Usuario -->
    <li class="dropdown">
        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
            <?=$this->transEsc("USUARIO")?>   
        </a>
        <ul class="dropdown-menu">
            <li><a href="<?=$this->url('home')?>MyResearch/Home"><?=$this->transEsc("Identificarse")?></a></li>
            <li><a href="<?=$this->url('home')?>MyResearch/Account"><?=$this->transEsc("Registrarse como usuario")?></a></li>
            <li><a href="<?=$this->url('home')?>MyResearch/Recover"><?=$this->transEsc("Recuperación de contraseña")?></a></li>
        </ul>
    </li>                    
    <!-- End Usuario -->
    
    <!-- Acerca de -->
    <li class="dropdown">
        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
        	<?=$this->transEsc("ACERCA DE")?> 
        	
        </a>
        <ul class="dropdown-menu">
            <!--  li><a href="<?=$this->url('home')?>Contents/Home?section=what">¿Qué es el buscador regional LA Referencia? </a></li-->       
            <li><a href="<?=$this->url('home')?>Contents/Home?section=how"><?=$this->transEsc("¿Cómo lo hacemos?")?></a></li>
            <li><a href="<?=$this->url('home')?>Contents/Home?section=who"><?=$this->transEsc("¿Quiénes participan?")?></a></li>
            <li><a href="<?=$this->url('home')?>Contents/Home?section=technology"><?=$this->transEsc("Software")?></a></li>
            <li><a href="<?=$this->url('home')?>Contents/Home?section=calidad"><?=$this->transEsc("Calidad Información")?></a></li>
            
            
        </ul>
    </li>                    
    <!-- End Acerca de -->
</ul>
