<ul class="nav navbar-nav">
    <!-- Home -->
    <li class=" active">
        <a href="javascript:void(0);">
            INICIO
        </a>
    </li>
    <!-- End Home -->

    <!-- Pages -->                        
    <li class="dropdown">
        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
            PAÍSES
        </a>
        <ul class="dropdown-menu">
            <li><a href="">Mapa de la Red</a></li>
            <li><a href="">Listado de Instituciones Cosechadas</a></li>
            <li><a href="">Estadística de Cosechas</a></li>
        </ul>
        
    </li>
    <!-- End Pages -->

    <!-- Features -->
    <li class="dropdown">
        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
            MATERIAL
        </a>
        <ul class="dropdown-menu">
            <li><a href="">Distribución del Material</a></li>
            <li><a href="">Distribución del Material Cosechado por Año</a></li>
            <li><a href="">Distribución de Licencias por País</a></li>
            <li><a href="">Nube de Términos</a></li>
        </ul>
        
    </li>
    <!-- End Features -->

    <!-- Explorar -->
    <li >
        <a href="javascript:void(0);">
            EXPLORAR
        </a>                            
    </li>
    <!-- End Explorar -->

    <!-- Buscar -->
    <li class="dropdown">
        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
            BUSCAR
        </a>
        <ul class="dropdown-menu">
            <li><a href="">Búsqueda Avanzada</a></li>
            <li><a href="">Historia de Búsqueda</a></li>
            <li><a href="">Consejos de Búsqueda</a></li>
        </ul>
    </li>
    <!-- End Buscar -->

    <!-- Usuario -->
    <li class="dropdown">
        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
            USUARIO
        </a>
        <ul class="dropdown-menu">
            <li><a href="">Identificarse</a></li>
            <li><a href="">Registrarse como usuario</a></li>
            <li><a href="">Recuperación de contraseña</a></li>
        </ul>
    </li>                    
    <!-- End Usuario -->
    
    <!-- Acerca de -->
    <li class="dropdown">
        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
            ACERCA DE
        </a>
        <ul class="dropdown-menu">
            <li><a href="">Cómo lo hacemos</a></li>
            <li><a href="">Quiénes participan</a></li>
            <li><a href="">Nodos nacionales</a></li>
        </ul>
    </li>                    
    <!-- End Acerca de -->
</ul>
