<ul>
<li class="pick-node">
  <a href="#">
	<img src="<?=$this->imageLink('nodes/oasis-bw.jpg')?>" alt=""> 
	<img class="pick-node-color" src="<?=$this->imageLink('nodes/oasis.jpg')?>" alt="">
  </a>
</li>
<li class="pick-node">
  <a href="#">
    <img src="<?=$this->imageLink('nodes/redicces-bw.jpg')?>" alt=""> 
    <img class="pick-node-color" src="<?=$this->imageLink('nodes/redicces.jpg')?>" alt="">
  </a>
</li>
<li class="pick-node">
  <a href="#">
    <img src="<?=$this->imageLink('nodes/snrd-bw.jpg')?>" alt=""> 
    <img class="pick-node-color" src="<?=$this->imageLink('nodes/snrd.jpg')?>" alt="">
  </a>
</li>
<li class="pick-node">
  <a href="#">
    <img src="<?=$this->imageLink('nodes/senescyt-bw.jpg')?>" alt=""> 
    <img class="pick-node-color" src="<?=$this->imageLink('nodes/senescyt.jpg')?>" alt="">
  </a>
</li>
<li class="pick-node">
  <a href="#">
    <img src="<?=$this->imageLink('nodes/sic-bw.jpg')?>" alt=""> 
    <img class="pick-node-color" src="<?=$this->imageLink('nodes/sic.jpg')?>" alt="">
  </a>
</li>
<li class="pick-node">
  <a href="#">
    <img src="<?=$this->imageLink('nodes/alicia-bw.jpg')?>" alt=""> 
    <img class="pick-node-color" src="<?=$this->imageLink('nodes/alicia.jpg')?>" alt="">
  </a>
</li>
<li class="pick-node">
  <a href="#">
    <img src="<?=$this->imageLink('nodes/remeri-bw.jpg')?>" alt=""> 
    <img class="pick-node-color" src="<?=$this->imageLink('nodes/remeri.jpg')?>" alt="">
  </a>
</li>
<li class="pick-node">
  <a href="#">
    <img src="<?=$this->imageLink('nodes/bdcol-bw.jpg')?>" alt=""> 
    <img class="pick-node-color" src="<?=$this->imageLink('nodes/bdcol.jpg')?>" alt="">
	  </a>
	</li>
</ul>