<div class="viewport" id="nodes-viewport">
	<ul class="sildes-list">
	<li>
	  <a target="_blank" href="http://repositoriosdigitales.mincyt.gob.ar/">
	    <img src="<?=$this->imageLink('nodes/snrd-bw.jpg')?>" alt=""> 
	    <img class="partner-color" src="<?=$this->imageLink('nodes/snrd.jpg')?>" alt="">
	  </a>
	</li>
	<li>
	  <a target="_blank" href="http://oasisbr.ibict.br/">
		<img src="<?=$this->imageLink('nodes/oasis-bw.jpg')?>" alt=""> 
		<img class="partner-color" src="<?=$this->imageLink('nodes/oasis.jpg')?>" alt="">
	  </a>
	</li>
	<li >
	  <a target="_blank" href="http://www.sic.informacioncientifica.cl/">
	    <img src="<?=$this->imageLink('nodes/sic-bw.jpg')?>" alt=""> 
	    <img class="partner-color" src="<?=$this->imageLink('nodes/sic.jpg')?>" alt="">
	  </a>
	</li>
	<li >
	  <a target="_blank" href="http://190.242.114.6:8082/inicio">
	    <img src="<?=$this->imageLink('nodes/snaac-bw.jpg')?>" alt=""> 
	    <img class="partner-color" src="<?=$this->imageLink('nodes/snaac.jpg')?>" alt="">
		  </a>
	</li>
	<li >
	  <a target="_blank" href="http://kimuk.conare.ac.cr/">
	    <img src="<?=$this->imageLink('nodes/kimuk-bw.png')?>" alt=""> 
	    <img class="partner-color" src="<?=$this->imageLink('nodes/kimuk.png')?>" alt="">
	  </a>
	</li>
	<li >
	  <a target="_blank" href="http://rraae.org.ec/">
	    <img src="<?=$this->imageLink('nodes/rraae_bw.png')?>" alt=""> 
	    <img class="partner-color" src="<?=$this->imageLink('nodes/rraae.png')?>" alt="">
	  </a>
	</li>
	<li >
	  <a target="_blank" href="http://www.remeri.org.mx/portal/index.html">
	    <img src="<?=$this->imageLink('nodes/remeri-bw.jpg')?>" alt=""> 
	    <img class="partner-color" src="<?=$this->imageLink('nodes/remeri.jpg')?>" alt="">
	  </a>
	</li>
	<li >
	  <a target="_blank" href="http://alicia.concytec.gob.pe/alicia/">
	    <img src="<?=$this->imageLink('nodes/alicia-bw.jpg')?>" alt=""> 
	    <img class="partner-color" src="<?=$this->imageLink('nodes/alicia.jpg')?>" alt="">
	  </a>
	</li>
	<li >
	  <a target="_blank" href="http://www.redicces.org.sv/jspui/">
	    <img src="<?=$this->imageLink('nodes/redicces-bw.jpg')?>" alt=""> 
	    <img class="partner-color" src="<?=$this->imageLink('nodes/redicces.jpg')?>" alt="">
	  </a>
	</li>
	</ul>
</div>