<ul>
				<li class="partner">
				  <a href="#">
				    <img src="<?=$this->imageLink('partners/oasis-bw.jpg')?>" alt=""> 
    <img class="partner-color" src="<?=$this->imageLink('partners/oasis.jpg')?>" alt="">
  </a>
</li>
<li class="partner">
  <a href="#">
    <img src="<?=$this->imageLink('partners/redicces-bw.jpg')?>" alt=""> 
    <img class="partner-color" src="<?=$this->imageLink('partners/redicces.jpg')?>" alt="">
  </a>
</li>
<li class="partner">
  <a href="#">
    <img src="<?=$this->imageLink('partners/snrd-bw.jpg')?>" alt=""> 
    <img class="partner-color" src="<?=$this->imageLink('partners/snrd.jpg')?>" alt="">
  </a>
</li>
<li class="partner">
  <a href="#">
    <img src="<?=$this->imageLink('partners/senescyt-bw.jpg')?>" alt=""> 
    <img class="partner-color" src="<?=$this->imageLink('partners/senescyt.jpg')?>" alt="">
  </a>
</li>
<li class="partner">
  <a href="#">
    <img src="<?=$this->imageLink('partners/sic-bw.jpg')?>" alt=""> 
    <img class="partner-color" src="<?=$this->imageLink('partners/sic.jpg')?>" alt="">
  </a>
</li>
<li class="partner">
  <a href="#">
    <img src="<?=$this->imageLink('partners/alicia-bw.jpg')?>" alt=""> 
    <img class="partner-color" src="<?=$this->imageLink('partners/alicia.jpg')?>" alt="">
  </a>
</li>
<li class="partner">
  <a href="#">
    <img src="<?=$this->imageLink('partners/remeri-bw.jpg')?>" alt=""> 
    <img class="partner-color" src="<?=$this->imageLink('partners/remeri.jpg')?>" alt="">
  </a>
</li>
<li class="partner">
  <a href="#">
    <img src="<?=$this->imageLink('partners/bdcol-bw.jpg')?>" alt=""> 
    <img class="partner-color" src="<?=$this->imageLink('partners/bdcol.jpg')?>" alt="">
	  </a>
	</li>
</ul>