<div id="viewport">
	<ul class="sildes-list">
		<li>
			<a target="_blank" href="http://www.redclara.net/">
				<img src="<?=$this->imageLink('partners/clara-bw.jpg')?>" alt=""> 
			    <img class="partner-color"  src="<?=$this->imageLink('partners/clara.jpg')?>" alt=""/>
		  	</a>
		</li>
		<li>
			<a target="_blank" href="http://www.mincyt.gob.ar/">
				<img src="<?=$this->imageLink('partners/mctip-bw.jpg')?>" alt=""> 
			    <img class="partner-color"  src="<?=$this->imageLink('partners/mctip.jpg')?>" alt=""/>
		  	</a>
		</li>
		
		 
		<li>
			<a target="_blank" href="http://www.ibict.br/">
				<img src="<?=$this->imageLink('partners/ibict-bw.jpg')?>" alt=""> 
			    <img class="partner-color"  src="<?=$this->imageLink('partners/ibict.jpg')?>" alt="">
		  	</a>
		</li>
		<li>
			<a target="_blank" href="http://www.conicyt.cl/">
				<img src="<?=$this->imageLink('partners/conicyt-bw.jpg')?>" alt=""> 
			    <img class="partner-color"  src="<?=$this->imageLink('partners/conicyt.jpg')?>" alt="">
		  	</a>
		</li>
		<li>
			<a target="_blank" href="http://www.mineducacion.gov.co/">
				<img src="<?=$this->imageLink('partners/mineducacion-bw.jpg')?>" alt=""> 
			    <img class="partner-color"  src="<?=$this->imageLink('partners/mineducacion.jpg')?>" alt="">
		  	</a>
		</li>
		<li>
			<a target="_blank" href="http://www.colciencias.gov.co/">
				<img src="<?=$this->imageLink('partners/colciencias-bw.jpg')?>" alt=""> 
			    <img class="partner-color"  src="<?=$this->imageLink('partners/colciencias.jpg')?>" alt="">
		  	</a>
		</li>
		<li>
			<a target="_blank" href="http://www.educacionsuperior.gob.ec/">
				<img src="<?=$this->imageLink('partners/snescti-bw.jpg')?>" alt=""> 
			    <img class="partner-color"  src="<?=$this->imageLink('partners/snescti.jpg')?>" alt="">
		  	</a>
		</li>
		<li>
			<a target="_blank" href="http://www.conacyt.mx/">
				<img src="<?=$this->imageLink('partners/conacyt-bw.jpg')?>" alt=""> 
			    <img class="partner-color"  src="<?=$this->imageLink('partners/conacyt.jpg')?>" alt="">
		  	</a>
		</li>
		<li>
			<a target="_blank" href="http://portal.concytec.gob.pe/">
				<img src="<?=$this->imageLink('partners/concytec-bw.jpg')?>" alt=""> 
			    <img class="partner-color"  src="<?=$this->imageLink('partners/concytec.jpg')?>" alt="">
		  	</a>
		</li>
		<li>
			<a target="_blank" href="http://www.cienciaytecnologia.edu.sv/">
				<img src="<?=$this->imageLink('partners/salvador-bw.jpg')?>" alt=""> 
			    <img class="partner-color"  src="<?=$this->imageLink('partners/salvador.jpg')?>" alt="">
		  	</a>
		</li>
		<li>
			<a target="_blank" href="http://www3.reacciun.ve/">
				<img src="<?=$this->imageLink('partners/cenit-bw.jpg')?>" alt=""> 
			    <img class="partner-color"  src="<?=$this->imageLink('partners/cenit.jpg')?>" alt="">
		  	</a>
		</li>
	</ul>
</div>

<div>
	<a id="simplePrevious">Previous</a>
<a id="simpleNext">Next</a>

</div>
	