<style>
td {
	padding: 10px;
}

p {
 margin-right: 30px;
 text-align: justify;
 }

</style>

<div class="row">
	<br />
</div>

<h2>Criterios de Calidad de LA Referencia - Julio 2015 </h2>

<div class="row">

	<div class="col-lg-11">

	    <br/>
	    
		<p>Calidad es una aproximación multidimensional que cubre aspectos
			de tipología de documentos, estándares de interoperabilidad,
			plataforma, servicios añadidos, entre otros. En ese marco, el
			siguiente texto explica los criterios de calidad de los documentos
			que son presentados en Acceso Abierto por LA Referencia.</p>
		<p>Cabe recordar que La Referencia se constituye en un acuerdo de
			autoridades de ciencia y tecnología que señala: “LA Referencia es una
			red que busca la participación de representantes de todos los países
			de América Latina y el Caribe con el fin de facilitar el acceso
			equitativo y dar visibilidad a la producción científica generada en
			las instituciones de educación superior y de investigación científica
			de la región.” (Buenos Aires, 2012)</p>
		<p>En su anexo indica que “las partes han acordado que para los
			efectos de este proyecto se entenderá por producción científica, los
			siguientes tipos documentales: artículos publicados en revistas
			arbitradas, las tesis de posgrado a nivel de maestría y doctorado y
			los informes técnicos.”</p>
		
		<p>Basándose en una estrategia red país, se cosechará la
			producción científica en Acceso Abierto de las instituciones “con las
			autorizaciones correspondientes para que, como mínimo, circulen a
			texto completo en Internet y de manera gratuita”. Finalmente,
			precisa: “las instituciones de educación superior y de investigación
			almacenarán su producción científica de acceso abierto en los
			repositorios institucionales, siendo responsabilidad de éstas
			mantener la calidad, disponibilidad y efectividad de dichos
			documentos” (Buenos Aires, 2012)</p>
	
		<p>
			<br />
		</p>
		
		<h3>Tipología</h3>
		
		<p></p>
		
		<p>Para asegurar la interoperabilidad La Referencia adoptó en sus
			inicios los estándares de Driver 2 que actualmente son mantenidos por
			OpenAire (OpenAire, 2013). De acuerdo a la tipología se definen los
			siguientes tipos que se cosechan, aunque los nodos nacionales pueden
			contener un conjunto mayor.</p>
		
		<br/>
		
		<table width="618" cellpadding="7" cellspacing="0">
			
			<col width="181">
			<col width="194">
			<col width="199">
			
			<tr valign="TOP">
				
				<td width="181" height="41" bgcolor="#5b9bd5"
					style="border-top: 1px solid #5b9bd5; border-bottom: 1px solid #5b9bd5; border-left: 1px solid #5b9bd5; border-right: none; ">
					
					<h5>Término Obligatorio</h5>
					
				</td>
				<td width="194" bgcolor="#5b9bd5"
					style="border-top: 1px solid #5b9bd5; border-bottom: 1px solid #5b9bd5; border-left: none; border-right: none; ">
					<h5>
						Versión permitida<br/>
						Recomendable
					</h5>
				</td>
				<td width="199" bgcolor="#5b9bd5"
					style="border-top: 1px solid #5b9bd5; border-bottom: 1px solid #5b9bd5; border-left: none; border-right: 1px solid #5b9bd5; ">
					<h5>
						Comentario
					</h5>
				</td>
			</tr>
			<tr valign="TOP">
				<td width="181" height="127" bgcolor="#deeaf6"
					style="border: 1px solid #9cc2e5;">
					<p>
						<span>article (Artículo)</span>
					</p>
					<br/>
					
					<p>
						<span>info:eu-repo/semantics/<br/>article </span>
					</p>
					<p>
						<br />
					</p>
				</td>
				<td width="194" bgcolor="#deeaf6"
					style="border: 1px solid #9cc2e5; ">
								
					<p>info:eu-repo/semantics/<br/>accepted</p>
					<p>
						<br />
					</p>
					<p>info:eu-repo/semantics/<br/>published</p>
					<p>
						<br />
					</p>
					<p>info:eu-repo/semantics/<br/>updated</p>
				
					<p>
						<br />
					</p>
				</td>
				<td width="199" bgcolor="#deeaf6"
					style="border: 1px solid #9cc2e5; ">
				
					<p>
						<span>Artículo o editorial publicado en una revista. Un
							artículo científico (a veces también llamado “paper”) es un
							trabajo destinado a la publicación en revistas especializadas que
							tuvo revisión por pares.</span>
					</p>
					<p>
						<span>Tiene como objetivo difundir, los resultados de una
							investigación realizada sobre un área determinada del
							conocimiento. También busca fomentar el desarrollo de métodos
							experimentales innovadores.</span>
					</p>
				</td>
			</tr>
			<tr valign="TOP">
				<td width="181" height="89" bgcolor="#ffffff"
					style="border: 1px solid #9cc2e5; ">
				
					<p>
						<span>masterThesis </span>
					</p>
					<p>
						<span>(Tesis de Master o Magister)</span>
					</p>
					<br/>
					<p>
						<span>info:eu-repo/semantics/<br/>masterThesis </span>
					</p>
					
					
				</td>
				<td width="194" bgcolor="#ffffff"
					style="border: 1px solid #9cc2e5; ">
				
					<p>info:eu-repo/semantics/<br/>accepted</p>
					<p>
						<br />
					</p>
					<p>info:eu-repo/semantics/<br/>published</p>
					<p>
						<br />
					</p>
					<p>info:eu-repo/semantics/<br/>updated</p>
					<p>
						<br />
					</p>
				</td>
				<td width="199" bgcolor="#ffffff"
					style="border: 1px solid #9cc2e5; ">
				
					<p>
						<span>Es un trabajo de investigación relacionado con los
							estudios cursados en un máster. Con este trabajo se adquiere el
							grado de Máster</span>
					</p>
					<p>
						<br />
					</p>
				</td>
			</tr>
			<tr valign="TOP">
				<td width="181" height="94" bgcolor="#deeaf6"
					style="border: 1px solid #9cc2e5; ">
				
					<p>
						<span>doctoralThesis </span>
					</p>
					<p>
						<span>(Tesis de Doctorado)<br /></span><br />
					</p>
					<p>
						<span>info:eu-repo/semantics/<br/>doctoralThesis </span>
					</p>
					<p>
						<br />
					</p>
				</td>
				<td width="194" bgcolor="#deeaf6"
					style="border: 1px solid #9cc2e5; ">
				
					<p>info:eu-repo/semantics/<br/>accepted</p>
					<p>
						<br />
					</p>
					<p>info:eu-repo/semantics/<br/>published</p>
					<p>
						<br />
					</p>
					<p>info:eu-repo/semantics/<br/>updated</p>
				</td>
				<td width="199" bgcolor="#deeaf6"
					style="border: 1px solid #9cc2e5; ">
		
					<p>
						<span>Es la tesis de más alto nivel. Es un estudio escrito
							tras cuatro o cinco años de investigación sobre un tema dado. La
							tesis doctoral es un trabajo inédito de investigación que permite
							acceder al grado de Doctor</span>
					</p>
					<p>
						<br />
					</p>
				</td>
			</tr>
			<tr valign="TOP">
				<td width="181" height="186" bgcolor="#ffffff"
					style="border: 1px solid #9cc2e5; ">
					<p>
						<span>Report<br/>(Reporte, Estudio, Informe, Memoria)
						</span>
					</p>
					
					<p>
						<br />info:eu-repo/semantics/<br/>report</p>

					<p>
						<br />
					</p>
				</td>
				<td width="194" bgcolor="#ffffff"
					style="border: 1px solid #9cc2e5; ">
					
					<p>info:eu-repo/semantics/<br/>published</p>
					<p>
						<br />
					</p>
					<p>info:eu-repo/semantics/<br/>updated</p>
					<p>
						<br />
					</p>
					
				</td>
				<td width="199" bgcolor="#ffffff"
					style="border: 1px solid #9cc2e5; ">
					<p>
						<span>Es una categoría amplia. Son informes o documentos
							de trabajo técnico o científico. Incluye algunos ejemplos como
							informes para agencias de financiación, documentación técnica,
							resultados de proyectos, etc.</span>
					</p>
					<p>
						<span>En el contexto de LA Referencia se aceptan los
							informes finales publicados de proyectos de I+D financiados total
							o parcialmente con fondos públicos y que han atravesado un
							proceso de evaluación. Es estratégico ya que permitirá conectar a
							futuro la investigación con la publicación.</span>
					</p>
				</td>
			</tr>
		</table>

		<p>
			<br />
		</p>
		
		<h3>
			Versiones de objetos digitales
		</h3>
	
		<br />
		<table width="618" cellpadding="7" cellspacing="0">
			<col width="165">
			<col width="423">
			<tr valign="TOP">
				<td width="165" height="28" bgcolor="#d9e2f3"
					style="border: 1px solid #8eaadb; ">
					<p>
						<br />
					</p>
					<p>acceptedVersion</p>
					<p>(versión aceptada)</p>
				</td>
				<td width="423" bgcolor="#d9e2f3"
					style="border: 1px solid #8eaadb; ">
					<p>
						<br />
					</p>
					<p>
						Una versión creada por el autor que incluye los comentarios de
						revisión por pares y es la aceptada para la publicación. También
						se la conoce como Manuscrito Aceptado; 
							Accepted Author Manuscript (AAM) o Accepted Manuscript (AM). Otra
						definición es &nbsp;post-print&nbsp;que ha pasado la revisión por
						pares. (La definición de pre-print se encuentra al final de este
						texto).
					</p>
					<p>
						<br />
					</p>
				</td>
			</tr>
			<tr valign="TOP">
				<td width="165" height="29" bgcolor="#ffffff"
					style="border: 1px solid #8eaadb; ">
					<p>
						<br />
					</p>
					<p>publishedVersion</p>
					<p>(versión publicada)</p>
				</td>
				<td width="423" bgcolor="#ffffff"
					style="border: 1px solid #8eaadb; ">
					<p></p>
					<p>
						Versión del editor. Es también denominada post-print; versión
						final pdf o versión publicada que incluye los aspectos de formato,
						numeración, etc. También se la conoce como Published
							Journal Article (PJA); Version of Record (VoR) o Publisher
						Generated Pdf
					</p>
					<p>
						<br />
					</p>
				</td>
			</tr>
			<tr valign="TOP">
				<td width="165" height="11" bgcolor="#d9e2f3"
					style="border: 1px solid #8eaadb; ">
					<p>
						<br />
					</p>
					<p>updatedVersion</p>
					<p>
						<br />
					</p>
				</td>
				<td width="423" bgcolor="#d9e2f3"
					style="border: 1px solid #8eaadb; ">
					<p>
						<br />
					</p>
					<p>Una versión actualizada desde la publicación</p>
				</td>
			</tr>
		</table>
		<p>
			<br />
		</p>
		<p>Es posible que la tipología se amplíe a futuro; pero dependerá
			de las decisiones del Consejo Directivo de LA Referencia.</p>
		
		<p>
			<a name="_GoBack"></a> Un aspecto clave es revisar la política de la
			editorial o revista para los artículos. Muchas aceptan la publicación
			en los repositorios de la versión publicada, otras sólo autorizan la
			versión aceptada o manuscrito con o sin tiempos de embargo. La
			política específica se puede revisar en el directorio Sherpa/Romeo de
			Políticas de copyright de las editoriales y autoarchivo.
			(Sherpa/Romeo). Por otra parte, existen legislaciones nacionales (a
			la fecha Argentina, Perú y México) y de fondos (Horizonte2020, NIH,
			etc.), que determinan políticas de archivo y disponibilidad en Acceso
			Abierto a través de repositorios que deben seguir los investigadores.
		</p>
		<p>
			<br />
		</p>
		<h3>Derechos y Licencias</h3>
			<br/>
		
		<p>LA Referencia solo cosechará la producción en acceso abierto o
			con embargo (ver vocabulario). No presentará los metadatos de
			documentos con acceso restringido o cerrado.</p>
		
		<p>La definición de Nivel de Acceso, según vocabulario controlado
			es:</p>
		<ul>
			<li><p>
					<span><span>info:eu-repo/semantics/openAccess</span></span>
				</p></li>
			<li><p>
					<span><span>info:eu-repo/semantics/embargoedAccess</span></span>
				</p></li>
		</ul>
		<p>
			<br />
		</p>
		<table width="625" cellpadding="7" cellspacing="0">
			<col width="208">
			<col width="387">
			<tr valign="TOP">
				<td width="208" height="9" bgcolor="#deeaf6"
					style="border: 1px solid #9cc2e5; ">
					<p>
						<br />
					</p>
					<p>
						openAccess <b>(acceso abierto) </b>
					</p>
					<p>
						<br />
					</p>
				</td>
				<td width="387" bgcolor="#deeaf6"
					style="border: 1px solid #9cc2e5; ">
					<p>
						<br />
					</p>
					<p>Acceso en línea sin restricciones técnicas o económicas al
						recurso.</p>
					<p>
						<br />
					</p>
				</td>
			</tr>
			<tr valign="TOP">
				<td width="208" height="44" bgcolor="#ffffff"
					style="border: 1px solid #9cc2e5; ">
					<p>
						<br />
					</p>
					<p>
						embargoedAccess <b>(embargado) </b>
					</p>
				</td>
				<td width="387" bgcolor="#ffffff"
					style="border: 1px solid #9cc2e5; ">
					<p>
						<br />
					</p>
					<p>El recurso es de acceso cerrado, hasta que sea liberado en
						acceso abierto en una fecha determinada</p>
					<p>
						<br />
					</p>
					<p>
						<br />
					</p>
				</td>
			</tr>
		</table>
		<p>
			<br />
		</p>
		<p>El Acta de Buenos Aires adhiere a la declaración de Berlín de
			Acceso Abierto cuyos párrafos claves se anexan al final de este
			texto.</p>
	
		<p>En relación a las condiciones de licencia se recomienda
			utilizar Creative Commons. Específicamente en el acuerdo de México se
			propone CC BY 3.0 NC para facilitar un amplio uso (Ciudad de México,
			2011). La decisión es nacional o de la institución; pero dado los
			objetivos de la más amplia circulación y uso del conocimiento se
			recomiendan versiones “liberales” de CC BY 3.0 o directamente
			utilizar CC 4.0 internacional.</p>
		<p>
			<br />
		</p>
		<h3>
			Control de calidad
		</h3>
		<br />
		<p>La calidad de los artículos que se ofrecen en acceso abierto es
			responsabilidad de cada nodo nacional bajo las pautas de su autoridad
			en ciencia y tecnología. Un criterio general es que son los artículos
			que el país considera válidos para la evaluación de sus
			investigadores y reflejan la producción científica del país.</p>
		<p>
			<br />
		</p>
		<p>En relación a las tesis de doctorado y magister existe un
			consenso amplio de su definición y el control se ejerce a nivel de
			metadatos.</p>
		
		<p>En la relación a los Informes ya en el acta de México (2011) se
			indicaba que eran Informes de Investigación. Caben en la tipología
			Report. Dada la posible amplitud de esta categoría, el espíritu del
			Acta de Buenos Aires y la adhesión a la declaración de Berlín, se
			realiza un trabajo país por país a fin de focalizar la cosecha en
			informes finales de proyectos de I+D publicados, financiados total o
			parcialmente por los gobiernos, con evaluación final.
			Estratégicamente permiten la trazabilidad de los resultados obtenidos
			con fondos públicos. Es factible que esta tipología se precise más el
			2016 según los acuerdos que logren respecto a la propuesta de COAR
			“Vocabulario Controlado de Tipos de Recursos“ (Coar, 2015)</p>
	
		<p>
			<br />
		</p>
		
		<h3>
			Referencias
		</h3>
		<br />
		
		
		<ul>
		<li>
			<a
				href="http://lareferencia.redclara.net/rfr/sites/default/files/AcuerdoBuenosAires.pdf">Buenos
				Aires (2012). Acuerdo de Cooperación Entre Altas Autoridades de
				Ciencia, Tecnología e Innovación de América Latina para la
				Constitución de LA Referencia</a>
		</li>
		
		<li>
			Ciudad de México (2011) - <a
				href="http://lareferencia.redclara.net/rfr/sites/default/files/AcuerdoMxDeclaracionAAOct2010.pdf"><span>
						Acuerdo de Acceso Abierto</span></a><span> </span> - <a
				href="http://lareferencia.redclara.net/rfr/sites/default/files/AcuerdosPromocionPoliticasAA.pdf"><span>
						Acuerdo de Promoción y Políticas</span></a>
		</li>
		
		<li>
			<a
				href="https://www.coar-repositories.org/news-media/coar-launches-draft-resource-type-vocabulary-for-open-access-repositories/"><span><span
					style="background: #ffffff">Coar (2013). COAR Launches Draft
						“Resource Type” Vocabulary for Open Access Repositories, julio
						2015.</span></span></a>
		</li>
		<li>
			<a
				href="https://guidelines.openaire.eu/wiki/OpenAIRE_Guidelines:_For_Literature_repositories"><span><span
					style="background: #ffffff">OpenAIRE (2013) OpenAIRE
						Guidelines for Literature Repository Managers 3, abril 2013</span></span></a>
		</li>
		<li>
			<b>Pre-Print:</b> Hay algunos editores que usan este término para
			denominar todas las formas de un artículo antes de publicación. A
			diferencia de ello, LA Referencia sigue la práctica académica más
			generalizada de que un pre-print es una versión de un artículo u otra
			publicación que se encuentra en borrador o ha sido enviada, pero no
			ha pasado por una revisión por pares u otras medidas de aseguramiento
			de calidad. Tampoco ha sido aceptada. Por ello, esta versión debe
			clasificarse como draft o submittedVersion y no serán cosechadas por
			LA Referencia. Específicamente, puede identificarse en el dc:type
			info:eu-repo/semantics/preprint
		</li>
	
		<li>
			<a href="http://www.sherpa.ac.uk/romeo/">Sherpa/Romeo: Políticas
				de copyright de las editoriales y autoarchivo.</a>

		</li>
		<li>
		<p>Declaración de Berlín de Acceso Abierto (extracto): Definición de una contribución de acceso abierto</p>
		<p>Para establecer el acceso abierto como un procedimiento
			meritorio, se requiere idealmente el compromiso activo de todos y
			cada uno de quienes producen conocimiento científico y mantienen el
			patrimonio cultural. Las contribuciones del acceso abierto incluyen
			los resultados de la investigación científica original, datos
			primarios y metadatos, materiales fuentes, representaciones digitales
			de materiales gráficos y pictóricos, y materiales eruditos en
			multimedia.</p>
		<p>Las contribuciones de acceso abierto deben satisfacer dos
			condiciones:</p>
		<ol>
			<li><p>El (los) autor(es) y depositario(s) de la propiedad
					intelectual de tales contribuciones deben garantizar a todos los
					usuarios por igual, el derecho gratuito, irrevocable y mundial de
					acceder a un trabajo erudito, lo mismo que licencia para copiarlo,
					usarlo, distribuirlo, transmitirlo y exhibirlo públicamente, y para
					hacer y distribuir trabajos derivativos, en cualquier medio digital
					para cualquier propósito responsable, todo sujeto al reconocimiento
					apropiado de autoría (los estándares de la comunidad continuarán
					proveyendo los mecanismos para hacer cumplir el reconocimiento
					apropiado y uso responsable de las obras publicadas, como ahora se
					hace), lo mismo que el derecho de efectuar copias impresas en
					pequeño número para su uso personal.</p></li>
			<li><p>Una versión completa del trabajo y todos sus
					materiales complementarios, que incluya una copia del permiso del
					que se habla arriba, en un conveniente formato electrónico
					estándar, se deposita (y así es publicado) en por lo menos un
					repositorio online, que utilice estándares técnicos aceptables
					(tales como las definiciones del Acceso Abierto), que sea apoyado y
					mantenido por una institución académica, sociedad erudita, agencia
					gubernamental, o una bien establecida organización que busque
					implementar el acceso abierto, distribución irrestricta,
					interoperabilidad y capacidad archivística a largo plazo.</p></li>
		</ol>
		<p>
			Texto completo:
	
			<a href="http://openaccess.mpg.de/Berlin-Declaration"><span>Berlin
					Declaration on Open Access to Knowledge in the Sciences and
					Humanities</span></a><span> - </span><a
				href="http://openaccess.mpg.de/67627/Berlin_sp.pdf">Versión en
				castellano</a> - <a
				href="http://openaccess.mpg.de/67693/BerlinDeclaration_pt.pdf">Versión
				en portugués</a>
		</p>
        </li>
	</div>
</div>
<!-- /.row -->