<style>
td {
	padding: 10px;
}

p {
 margin-right: 30px;
 text-align: justify;
 }

</style>

<div class="row">
	<br />
</div>

<h2>Critérios de Qualidade de LA Referencia - Julho 2015 </h2>

<div class="row">

	<div class="col-lg-11">

	    <br/>
	    
		<p>Qualidade é uma aproximação multidimensional que cobre aspectos
			de tipologia de documentos, padrões de interoperabilidade,
			plataforma, serviços agregados, entre outros. Nesse contexto, o
			seguinte texto explica os critérios de qualidade dos documentos
			apresentados em Acesso Aberto por LA Referencia.</p>
		<p>Cabe recordar que LA Referencia se constitui em um acordo de 			autoridades de Ciência e Tecnologia que afirma: “LA Referencia é uma
			rede que busca a participação de representantes de todos os países
			da América Latina e do Caribe com o fim de facilitar o acesso
			equitativo e de dar visibilidade à produção científica gerada nas
			instituições de educação superior e de pesquisa científica da região.” (Buenos Aires, 2012)</p>
		<p>Seu anexo indica que “as partes acordaram que, para os efeitos deste projeto, se entenderá por produção científica os
			seguintes tipos documentais: artigos publicados em revistas
			arbitradas, as teses de pós-graduação a nível de mestrado e doutorado e 
			os relatórios técnicos.”</p>
		
		<p>Baseando-se em uma estratégia rede-país, se coletará a produção científica em Acesso Aberto das instituições “com as
			autorizações correspondentes para que, minimamente, circule o
			texto completo na Internet, de maneira gratuita”. Finalmente,
			precisa: “as instituições de educação superior e de pesquisa
			armazenarão sua produção científica de acesso aberto nos
			repositórios institucionais, sendo responsabilidade destas
			manter a qualidade, a disponibilidade e a efetividade destes
			documentos” (Buenos Aires, 2012)</p>
	
		<p>
			<br />
		</p>
		
		<h3>Tipologia</h3>
		
		<p></p>
		
		<p>Para assegurar a interoperabilidade, LA Referencia adotou em seu início os padrões de Driver 2 que atualmente são mantidos por
			OpenAire (OpenAire, 2013). De acordo com a tipologia se definem os
			seguintes tipos que se colhem, ainda que os nodos nacionais possam conter um conjunto maior.</p>
		
		<br/>
		
		<table width="618" cellpadding="7" cellspacing="0">
			
			<col width="181">
			<col width="194">
			<col width="199">
			
			<tr valign="TOP">
				
				<td width="181" height="41" bgcolor="#5b9bd5"
					style="border-top: 1px solid #5b9bd5; border-bottom: 1px solid #5b9bd5; border-left: 1px solid #5b9bd5; border-right: none; ">
					
					<h5>Término Obrigatório</h5>
					
				</td>
				<td width="194" bgcolor="#5b9bd5"
					style="border-top: 1px solid #5b9bd5; border-bottom: 1px solid #5b9bd5; border-left: none; border-right: none; ">
					<h5>
						Versão permitida<br/>
						Recomendável
					</h5>
				</td>
				<td width="199" bgcolor="#5b9bd5"
					style="border-top: 1px solid #5b9bd5; border-bottom: 1px solid #5b9bd5; border-left: none; border-right: 1px solid #5b9bd5; ">
					<h5>
						Comentário
					</h5>
				</td>
			</tr>
			<tr valign="TOP">
				<td width="181" height="127" bgcolor="#deeaf6"
					style="border: 1px solid #9cc2e5;">
					<p>
						<span>article (Artigo)</span>
					</p>
					<br/>
					
					<p>
						<span>info:eu-repo/semantics/<br/>article </span>
					</p>
					<p>
						<br />
					</p>
				</td>
				<td width="194" bgcolor="#deeaf6"
					style="border: 1px solid #9cc2e5; ">
								
					<p>info:eu-repo/semantics/<br/>accepted</p>
					<p>
						<br />
					</p>
					<p>info:eu-repo/semantics/<br/>published</p>
					<p>
						<br />
					</p>
					<p>info:eu-repo/semantics/<br/>updated</p>
				
					<p>
						<br />
					</p>
				</td>
				<td width="199" bgcolor="#deeaf6"
					style="border: 1px solid #9cc2e5; ">
				
					<p>
						<span>Artigo ou editorial publicado em uma revista. Um
							artigo científico (às vezes também chamado “paper”) é um
							trabalho destinado à publicação em revistas especializadas que
							teve revisão por pares.</span>
					</p>
					<p>
						<span>Tem como objetivo difundir os resultados de uma
							pesquisa realizada sobre uma área determinada do
							conhecimento. Também busca fomentar o desenvolvimento de métodos
							experimentais inovadores.</span>
					</p>
				</td>
			</tr>
			<tr valign="TOP">
				<td width="181" height="89" bgcolor="#ffffff"
					style="border: 1px solid #9cc2e5; ">
				
					<p>
						<span>masterThesis </span>
					</p>
					<p>
						<span>(Tese de Mestrado)</span>
					</p>
					<br/>
					<p>
						<span>info:eu-repo/semantics/<br/>masterThesis </span>
					</p>
					
					
				</td>
				<td width="194" bgcolor="#ffffff"
					style="border: 1px solid #9cc2e5; ">
				
					<p>info:eu-repo/semantics/<br/>accepted</p>
					<p>
						<br />
					</p>
					<p>info:eu-repo/semantics/<br/>published</p>
					<p>
						<br />
					</p>
					<p>info:eu-repo/semantics/<br/>updated</p>
					<p>
						<br />
					</p>
				</td>
				<td width="199" bgcolor="#ffffff"
					style="border: 1px solid #9cc2e5; ">
				
					<p>
						<span>É um trabalho de pesquisa relacionado com os
							estudos cursados em um Mestrado. Com este trabalho se adquire o
							grau de Mestre</span>
					</p>
					<p>
						<br />
					</p>
				</td>
			</tr>
			<tr valign="TOP">
				<td width="181" height="94" bgcolor="#deeaf6"
					style="border: 1px solid #9cc2e5; ">
				
					<p>
						<span>doctoralThesis </span>
					</p>
					<p>
						<span>(Tese de Doutorado)<br /></span><br />
					</p>
					<p>
						<span>info:eu-repo/semantics/<br/>doctoralThesis </span>
					</p>
					<p>
						<br />
					</p>
				</td>
				<td width="194" bgcolor="#deeaf6"
					style="border: 1px solid #9cc2e5; ">
				
					<p>info:eu-repo/semantics/<br/>accepted</p>
					<p>
						<br />
					</p>
					<p>info:eu-repo/semantics/<br/>published</p>
					<p>
						<br />
					</p>
					<p>info:eu-repo/semantics/<br/>updated</p>
				</td>
				<td width="199" bgcolor="#deeaf6"
					style="border: 1px solid #9cc2e5; ">
		
					<p>
						<span>É a tese de mais alto nível. É um estudo escrito
							depois de quatro ou cinco anos de pesquisa sobre um tema dado. A
							tese de doutorado é um trabalho de pesquisa inédito que concede 
							o grau de Doutor</span>
					</p>
					<p>
						<br />
					</p>
				</td>
			</tr>
			<tr valign="TOP">
				<td width="181" height="186" bgcolor="#ffffff"
					style="border: 1px solid #9cc2e5; ">
					<p>
						<span>Report<br/>(Reporte, Estudo, Relatório, Memória)
						</span>
					</p>
					
					<p>
						<br />info:eu-repo/semantics/<br/>report</p>

					<p>
						<br />
					</p>
				</td>
				<td width="194" bgcolor="#ffffff"
					style="border: 1px solid #9cc2e5; ">
					
					<p>info:eu-repo/semantics/<br/>published</p>
					<p>
						<br />
					</p>
					<p>info:eu-repo/semantics/<br/>updated</p>
					<p>
						<br />
					</p>
					
				</td>
				<td width="199" bgcolor="#ffffff"
					style="border: 1px solid #9cc2e5; ">
					<p>
						<span>É uma categoria ampla. São relatórios ou documentos
							de trabalho técnico ou científico. Inclui alguns exemplos como
							relatórios para agências de financiamento, documentação técnica,
							resultados de projetos, etc.</span>
					</p>
					<p>
						<span>No contexto de LA Referencia se aceitam os
							relatórios finais publicados de projetos I+D financiados total
							ou parcialmente com fundos públicos e que passaram por um
							processo de avaliação. É estratégico, já que permitirá conectar, no
							futuro, a pesquisa com a  publicação.</span>
					</p>
				</td>
			</tr>
		</table>

		<p>
			<br />
		</p>
		
		<h3>
			Versões de objetos digitais
		</h3>
	
		<br />
		<table width="618" cellpadding="7" cellspacing="0">
			<col width="165">
			<col width="423">
			<tr valign="TOP">
				<td width="165" height="28" bgcolor="#d9e2f3"
					style="border: 1px solid #8eaadb; ">
					<p>
						<br />
					</p>
					<p>acceptedVersion</p>
					<p>(versão aceita)</p>
				</td>
				<td width="423" bgcolor="#d9e2f3"
					style="border: 1px solid #8eaadb; ">
					<p>
						<br />
					</p>
					<p>
						Uma versão criada pelo autor que inclui os comentários de
						revisão por pares e é aceita para publicação. Também
						é conhecida como Manuscrito Aceito; 
							Accepted Author Manuscript (AAM) ou Accepted Manuscript (AM). Outra
						definição é &nbsp;post-print&nbsp;que passou a revisão por
						pares. (A definição de pre-print se encontra no final deste
						texto).
					</p>
					<p>
						<br />
					</p>
				</td>
			</tr>
			<tr valign="TOP">
				<td width="165" height="29" bgcolor="#ffffff"
					style="border: 1px solid #8eaadb; ">
					<p>
						<br />
					</p>
					<p>publishedVersion</p>
					<p>(versão publicada)</p>
				</td>
				<td width="423" bgcolor="#ffffff"
					style="border: 1px solid #8eaadb; ">
					<p></p>
					<p>
						Versão do editor. É também denominada post-print; versão
						final pdf ou versão publicada que inclui os aspectos de formato,
						numeração, etc. Também é conhecida como <a
							href="http://www.elsevier.com/about/open-access/open-access-policies/article-posting-policy#published-journal-article">Published
							Journal Article (PJA)</a>; Version of Record (VoR) ou Publisher
						Generated Pdf
					</p>
					<p>
						<br />
					</p>
				</td>
			</tr>
			<tr valign="TOP">
				<td width="165" height="11" bgcolor="#d9e2f3"
					style="border: 1px solid #8eaadb; ">
					<p>
						<br />
					</p>
					<p>updatedVersion</p>
					<p>
						<br />
					</p>
				</td>
				<td width="423" bgcolor="#d9e2f3"
					style="border: 1px solid #8eaadb; ">
					<p>
						<br />
					</p>
					<p>Uma versão atualizada depois da publicação</p>
				</td>
			</tr>
		</table>
		<p>
			<br />
		</p>
		<p>É possível que a tipologia se amplie no futuro, mas isso dependerá das decisões do Conselho Diretor de LA Referencia.</p>
		
		<p>
			<a name="_GoBack"></a> Um aspecto chave é revisar a política da
			editorial ou revista para os artigos. Muitas aceitam a publicação
			nos repositórios da versão publicada, outras somente autorizam a
			versão aceita ou manuscrito com ou sem tempos de embargo. A
			política específica se pode revisar no diretório Sherpa/Romeo de
			Políticas de copyright das editoriais e auto-arquivo.
			(Sherpa/Romeo). Por outra parte, existem legislações nacionais (no
			momento em Argentina, Peru e México) e de financiamento (Horizonte2020, NIH,
			etc.), que determinam políticas de arquivo e disponibilidade em Acesso
			Aberto através de repositórios que devem seguir os pesquisadores.
		</p>
		<p>
			<br />
		</p>
		<h3>Direitos e Licenças</h3>
			<br/>
		
		<p>LA Referencia coletará somente a produção em acesso aberto ou
			com embargo (ver vocabulário). Não apresentará os metadados de
			documentos com acesso restrito ou fechado.</p>
		
		<p>A definição do Nível de Acesso, segundo vocabulário controlado
			é:</p>
		<ul>
			<li><p>
					<span><span>info:eu-repo/semantics/openAccess</span></span>
				</p></li>
			<li><p>
					<span><span>info:eu-repo/semantics/embargoedAccess</span></span>
				</p></li>
		</ul>
		<p>
			<br />
		</p>
		<table width="625" cellpadding="7" cellspacing="0">
			<col width="208">
			<col width="387">
			<tr valign="TOP">
				<td width="208" height="9" bgcolor="#deeaf6"
					style="border: 1px solid #9cc2e5; ">
					<p>
						<br />
					</p>
					<p>
						openAccess <b>(acesso aberto) </b>
					</p>
					<p>
						<br />
					</p>
				</td>
				<td width="387" bgcolor="#deeaf6"
					style="border: 1px solid #9cc2e5; ">
					<p>
						<br />
					</p>
					<p>Acesso online sem restrições técnicas ou econômicas ao
						recurso.</p>
					<p>
						<br />
					</p>
				</td>
			</tr>
			<tr valign="TOP">
				<td width="208" height="44" bgcolor="#ffffff"
					style="border: 1px solid #9cc2e5; ">
					<p>
						<br />
					</p>
					<p>
						embargoedAccess <b>(embargado) </b>
					</p>
				</td>
				<td width="387" bgcolor="#ffffff"
					style="border: 1px solid #9cc2e5; ">
					<p>
						<br />
					</p>
					<p>O recurso é de acesso fechado, até que seja liberado em
						acesso abeerto em uma data determinada</p>
					<p>
						<br />
					</p>
					<p>
						<br />
					</p>
				</td>
			</tr>
		</table>
		<p>
			<br />
		</p>
		<p>A Ata de Buenos Aires adere à declaração de
			Acesso Aberto de Berlim, cujos parágrafos chave se anexam ao final deste 
			texto.</p>
	
		<p>Em relação às condições de licença se recomenda
			utilizar Creative Commons. Especificamente no acordo de México se
			propõe CC BY 3.0 NC para facilitar um amplo uso (Cidade do México,
			2011). A decisão é nacional ou da instituição; mas dados os
			objetivos da mais ampla circulação e uso do conhecimento se
			recomendam versões “liberais” de CC BY 3.0 ou diretamente
			utilizar CC 4.0 internacional.</p>
		<p>
			<br />
		</p>
		<h3>
			Controle de qualidade
		</h3>
		<br />
		<p>A qualidade dos artigos oferecidos em acesso aberto é
			responsabilidade de cada nodo nacional sob as pautas de sua autoridade
			em Ciência e Tecnologia. Um critério geral é que são os artigos			que o país considera válidos para a avaliação de seus pesquisadores e  refletem a produção científica do país.</p>
		<p>
			<br />
		</p>
		<p>Em relação às teses de doutorado e mestrado existe um amplo consenso de sua definição e o controle é exercido a nível de metadados.</p>
		
		<p>Em relação aos Relatórios, já na Ata do México (2011) se
			indicava que eram Relatórios de Pesquisa. Cabem na tipologia
			Report. Dada a possível amplitude desta categoria, o espírito da
			Ata de Buenos Aires e a adesão à declaração de Berlim, se
			realiza um trabalho país por país a fim de enfocar a colheita em 
			relatórios finais de projetos de I+D publicados, financiados total o
			parcialmente pelos governos, com avaliação final.
			Estrategicamente permitem a rastreabilidade dos resultados obtidos
			com fundos públicos. É factível que esta tipologia seja mais necessária em
			2016, segundo os acordos que digam respeito à proposta de COAR
			“Vocabulário Controlado de Tipos de Recursos“ (Coar, 2015)</p>
	
		<p>
			<br />
		</p>
		
		<h3>
			Referências
		</h3>
		<br />
		
		
		<ul>
		<li>
			<a
				href="http://lareferencia.redclara.net/rfr/sites/default/files/AcuerdoBuenosAires.pdf">Buenos
				Aires (2012). Acordo de Cooperação Entre Altas Autoridades de
				Ciência, Tecnologia e Inovação da América Latina para a
				Constituição de LA Referencia</a>
		</li>
		
		<li>
			Cidade do México (2011) - <a
				href="http://lareferencia.redclara.net/rfr/sites/default/files/AcuerdoMxDeclaracionAAOct2010.pdf"><span>
						Acordo de Acesso Aberto</span></a><span> </span> - <a
				href="http://lareferencia.redclara.net/rfr/sites/default/files/AcuerdosPromocionPoliticasAA.pdf"><span>
						Acordo de Promoção e Políticas</span></a>
		</li>
		
		<li>
			<a
				href="https://www.coar-repositories.org/news-media/coar-launches-draft-resource-type-vocabulary-for-open-access-repositories/"><span><span
					style="background: #ffffff">Coar (2013). COAR Launches Draft
						“Resource Type” Vocabulary for Open Access Repositories, julho
						2015.</span></span></a>
		</li>
		<li>
			<a
				href="https://guidelines.openaire.eu/wiki/OpenAIRE_Guidelines:_For_Literature_repositories"><span><span
					style="background: #ffffff">OpenAIRE (2013) OpenAIRE
						Guidelines for Literature Repository Managers, 3 de abril de 2013</span></span></a>
		</li>
		<li>
			<b>Pre-Print:</b> Há alguns editores que usam este termo para
			denominar todas as formas de um artigo antes da publicação. À
			diferença deles, LA Referencia segue a prática acadêmica mais
			conhecida de que um pre-print é uma versão de um artigo ou outra
			publicação que foi apagada ou foi enviada, mas que não passou por pares ou outras medidas de asseguramento
			de qualidade. Tampouco foi aceita. Por isso, esta versão deve
			classificar-se como draft ou submittedVersion e não será colhida por
			LA Referencia. Especificamente, pode identificar-se no dc:type
			info:eu-repo/semantics/preprint
		</li>
	
		<li>
			<a href="http://www.sherpa.ac.uk/romeo/">Sherpa/Romeo: Políticas
				de copyright das editoriais e auto-arquivo.</a>

		</li>
		<li>
		<p>Declaração de Berlim de Acesso Aberto (extrato): Definição de uma contribuição de acesso aberto</p>
		<p>Para estabelecer o acesso aberto como um procedimento
			meritório, se requer idealmente o compromisso ativo de todos aqueles que produzem conhecimento científico e mantém o
			patrimônio cultural. As contribuções do acesso aberto incluem
			os resultados da pesquisa científica original, dados
			primários e metadatos, materiais fonte, representações digitais
			de materiais gráficos e pictóricos, e materiais eruditos em
			multimídia.</p>
		<p>As contribuições de acesso aberto devem satisfazer duas
			condições:</p>
		<ol>
			<li><p>O(s) autor(es) e depositário(s) da propriedade
					intelectual de tais contribuições devem garantir a todos os
					usuários por igual, o direito gratuito, irrevogável e  mundial de
					acessar um trabalho erudito, assim como licença para copiá-lo,
					usá-lo, distribuí-lo, transmití-lo e exibí-lo publicamente, e para
					fazer e distribuir trabalhos derivativos, em qualquer meio digital
					para qualquer propósito responsável, tudo sujeito ao reconhecimento
					apropriado de autoria (os padrões da comunidade continuarão
					provendo os mecanismos para fazer cumprir o reconhecimento e o uso responsável 
					das obras publicadas, tal como agora)			assim como o direito de efetuar cópias impressas em pequeno número para uso pessoal.</p></li>
			<li><p>Uma versão completa do trabalho e todos seus
					materiais complementares, que inclua uma cópia da permissão do 
					que se expõe acima, em um conveniente formato eletrônico
					padrão, se deposita (e assim é publicado) em pelo menos um
					repositório online, que utilize padrões técnicos aceitáveis
					(tais como as definições do Acesso Aberto), que seja apoiado e
					mantido por uma instituição acadêmica, sociedade erudita, agência
					governamental, ou uma bem estabelecida organização que busque
					implementar o acesso aberto, distribuição irrestrita,
					interoperabilidade e capacidade arquivística em longo plazo.</p></li>
		</ol>
		<p>
			Texto completo:
	
			<a href="http://openaccess.mpg.de/Berlin-Declaration"><span>Berlin
					Declaration on Open Access to Knowledge in the Sciences and
					Humanities</span></a><span> - </span><a
				href="http://openaccess.mpg.de/67627/Berlin_sp.pdf">Versión en
				castellano</a> - <a
				href="http://openaccess.mpg.de/67693/BerlinDeclaration_pt.pdf">Versión
				en portugués</a>
		</p>
        </li>
	</div>
</div>
<!-- /.row -->
