

<div class="row"><br/></div>
   
<h2>Como é feito?</h2>
	
<div class="row"><br/>
            
	<div class="col-lg-11">
    
	    <p>Para que os usuários possam ter acesso ao texto completo dos materiais acadêmicos que se encontram nos repositórios institucionais dos nove países membros de LA Referencia, trabalhamos previamente em processos organizativos e técnicos que garantem a qualidade dos dados, centrando-nos em várias fases:</p>
		
		<ul>
			<li><b>Entramos em acordo:</b> os países membros subscrevem acordos regionais para definir políticas comuns e padrões de qualidade com o objetivo de construir uma rede federada de repositórios de documentação científica.</li>
			<li><b>Colhemos:</b> periodicamente recolhemos os registros de metadados oferecidos pelos repositórios da rede, mantendo atualizados os conteúdos oferecidos no portal.</li>
			<li><b>Validamos:</b> geramos mecanismos para assegurar a qualidade da informação publicada, de acordo com as diretrizes de qualidade acordadas com os países membros.</li>
			<li><b>Federamos:</b> realizamos um processo de integração e indexação dos conteúdos colhidos, disponibilizando aos usuários serviços de busca com acesso unificado.</li> 
			<li><b>Ofrecemos:</b> no portal público de busca, disponibilizamos a recuperação da informação e o acesso aos documentos em seu repositório institucional original, em um ambiente de constante melhoria .</li>
	    </ul>            
             
    </div>
</div>                
<!-- /.row -->