<style>
h4 {
margin-bottom: 0px;
margin-top: 30px;

}

h5 {
font-size: 15px;
font-weight: bold;
}

p {
	text-align: justify;
}

#static-content li {
margin-bottom: 0px;
}
</style>

<div class="row"><br/></div>
   
<h2>Nodos nacionales</h2>
	
<div class="row"><br/>

	<div class="col-lg-11">
	    
	<p>Os nodos nacionais constituem as redes de repositórios promovidas entre os países membros, por meio de iniciativas adaptadas a cada contexto. Seguindo os padrões internacionais, técnicos e organizacionais, as redes de cada país são uma ponte efetiva para integrar conteúdos no buscador de documentos científicos LA Referencia</p>  
	
	<h4><a href="http://repositoriosdigitales.mincyt.gob.ar">Nodo Argentina: Sistema Nacional de Repositorios Digitales –SNRD-</a></h4>
	<a href="#Argentina">Ver resumo e instituições</a>
	
	<h4><a href="http://oasisbr.ibict.br/">Nodo Brasil: Portal Brasileiro de Acesso Aberto à Informação Científica –oasisbr-</a></h4>
	<a href="#Brasil">Ver resumo e instituições</a>
	
	<h4><a href="http://bdcol.org/">Nodo Colombia: Biblioteca Digital Colombiana –BDCOL-</a></h4>
	<a href="#Colombia">Ver resumo e instituições</a>
	
	<h4><a href="http://www.sic.informacioncientifica.cl/">Nodo Chile: Sistema de Información Científica –SIC-</a></h4>
	<a href="#Chile">Ver resumo e instituições</a>
	
	<h4><a href="http://rraae.org.ec/">Nodo Ecuador:  Red de Repositorios Abiertos del Ecuador - RRAAE</a></h4>
	<a href="#Ecuador">Ver resumo e instituições</a>
	
	<h4><a href="http://www.redicces.org.sv">Nodo El Salvador: Repositorio Digital de Ciencia y Cultura de El Salvador –REDICCES-</a></h4>
	<a href="#ElSalvador">Ver resumo e instituições</a>
	
	<h4><a href="http://www.remeri.org.mx/portal/index.html">Nodo México: Red Mexicana de Repositorios Institucionales –REMERI-</a></h4>
	<a href="#Mexico">Ver resumo e instituições</a>
	
	<h4><a href="http://alicia.concytec.gob.pe/alicia/">Nodo Perú: Acceso Libre a Información Científica para la Innovación</a></h4>
	<a href="#Peru">Ver resumo e instituições</a>
	
 
		
	</div>
</div>  

<br/><br/>
<h2>Relação de instituições colhidas</h2>

<div class="row">

	<div class="col-lg-11">
	    
	<h4><a name="Argentina">Nodo Argentina: Sistema Nacional de Repositorios Digitales –SNRD-</a></h4>
	<br/>
	<p>O SRND promove, na Argentina, o acesso aberto e o intercambio da produção científico-tecnológica produzida no país. Além disso, as instituições membro podem solicitar financiamento para criar/fortalecer seus repositórios digitais e para a formação de recursos humanos.</p>
	<p>Seu propósito é formar uma rede interoperável de repositórios digitais em Ciência e Tecnologia na Argentina, a partir do estabelecimento de políticas, padrões e protocolos comuns a todos os integrantes do sistema.</p>
	<p>O SNRD conta com mais de 20 mil documentos de 12 repositórios argentinos. Esta é uma iniciativa do Ministério de Ciência, Tecnologia e Inovação Produtiva, em conjunto com o Conselho Interinstitucional de Ciências e Tecnologia (CICyT) através de seus representantes no Conselho Assessor da Biblioteca Eletrônica de Ciência e Tecnologia.</p>

	<h5>Links úteis</h5>
	<ul>
		<li><a href="http://repositoriosdigitales.mincyt.gob.ar">SNRD</a></li>
		<li><a href="http://www.mincyt.gob.ar/">Ministerio de Ciencia, Tecnología e Innovación Productiva</a></li>
		<li><a href="http://www.cicyt.mincyt.gob.ar/">Consejo Interinstitucional de Ciencia y Tecnología (CICyT)</a></li>
		<li><a href="http://www.biblioteca.mincyt.gov.ar/">Biblioteca Electrónica de Ciencia y Tecnología</a></li>		
	</ul>
	
	<h5>Instituições colhidas</h5>
	<ul>
		<li>	Universidad de la Fraternidad de Agrupaciones Santo Tomás de Aquino (UFASTA)	</li>
		<li>	Universidad Nacional de Buenos Aires. Facultad de Ciencias Exactas y Naturales (UBA-FCEN)	</li>
		<li>	Universidad Nacional de La Plata (UNLP)	</li>
		<li>	Universidad Nacional de La Plata. Facultad de Humanidades y Ciencias de la Educación (UNLP-FAHCE)	</li>
		<li>	Universidad Nacional de Lanús (UNLA)	</li>
		<li>	Universidad Nacional de Mar del Plata. Facultad de Ciencias Económicas y Sociales (UNMdP. FCEyS)	</li>
		<li>	Universidad Nacional del Litoral (UNL)	</li>
	</ul>
	
	
	<h4><a name="Brasil">Nodo Brasil: Portal Brasileiro de Acesso Aberto à Informação Científica –oasisbr-</a></h4>
	<br/>
	<p>O Portal Brasileiro de Acesso Aberto à Informação Científica – oasisbr- é um mecanismo de busca multidisciplinar que permite o acesso gratuito à produção científica de autores vinculados a universidades e institutos de pesquisa brasileiros.</p> 	
	<p>Oasisbr é um dos resultados dos esforços do Ibict, apoiados pela Financiadora de Estudos e Projetos - FINEP, para a inserção da ciência brasileira do contexto acesso aberto à informação científica.</p>

	<h5>Links úteis</h5>
	<ul>
		<li><a href="http://oasisbr.ibict.br/">Portal Brasileiro de Acesso Aberto à Informação Científica – oasisbr</a></li>
		<li><a href="http://www.ibict.br/">Ibict</a></li>
		<li><a href="http://www.finep.gov.br/ ">Financiadora de Estudos e Projetos - FINEP</a></li>
	</ul>
	
	<h5>Instituições colhidas</h5>
	<ul>
		<li>	Universidade Aberta do SUS	</li>
		<li>	Universidade Metodista de Sao Paulo	</li>
		<li>	Universidade Municipal de São Caetano do Sul	</li>
		<li>	Instituto Brasileiro de Informação em Ciência e Tecnologia	</li>
		<li>	Fundação Centro Tecnológico de Minas Gerais (Portugal)	</li>
		<li>	Universidade Federal de Pelotas	</li>
		<li>	Empresa Brasileira de Pesquisa Agropecuária	</li>
		<li>	Universidade Federal do Rio Grande do Sul	</li>
		<li>	Universidade Federal Fluminense	</li>
		<li>	Museu Paraense Emílio Goeldi	</li>
		<li>	Universidade Federal do Rio Grando do Norte	</li>
		<li>	Universidade de São Paulo	</li>
		<li>	Universidade Federal de Viçosa	</li>
		<li>	Universidade Tecnológica Federal do Paraná	</li>
		<li>	Centro de Tecnologia da Informação Renato Archier	</li>
		<li>	Fundação Centro Tecnológico de Minas Gerais (CETEC)	</li>
		<li>	Instituto Nacional de Tecnologia	</li>
		<li>	Universidade Federal de Grande Dourados	</li>
		<li>	Universidade Federal do Maranhão	</li>
		<li>	Universidade de Brasília	</li>
		<li>	SciELO Brasil-Bireme	</li>
		<li>	Universidade Estadual de Ponta Grossa	</li>
	</ul>
	
	<h4><a name="Colombia">Nodo Colombia: Biblioteca Digital Colombiana –BDCOL-</a></h4>
	<br/>

	<p>BDCOL surgiu em 2007 como uma iniciativa das instituições de educação superior da Colômbia para promover o acesso ao conhecimento gerado naquele país. O Departamento Administrativo de Ciência, Tecnologia e Inovação de COLCIENCIAS, o Ministério de Educação Nacional e a Rede Nacional Acadêmica de Tecnologia Avançada – RENATA – quiseram fortalecer esta iniciativa de repositórios na Colômbia, por meio de uma Estratégia Nacional de Acesso Aberto ao Conhecimento, canalizada por BDCOL.</p>
	
	<h5>Links úteis</h5>
	<ul>
		<li><a href="http://bdcol.org/">BDCOL</a></li>
		<li><a href="http://www.colciencias.gov.co/">COLCIENCIAS</a></li>
		<li><a href="http://www.mineducacion.gov.co/">Ministerio de Educación Nacional</a></li>
		<li><a href="http://www.renata.edu.co/ ">RENATA</a></li>
		
	</ul>
	
	<h5>Instituições colhidas</h5>
	<ul>
		<li>	ACFO, Asociación Colombiana de Facultades de Odontología 	</li>
		<li>	ACTA, Asociación Colombiana de Ciencia y Tecnología de Alimentos 	</li>
		<li>	Fundación Universitaria Konrad Lorenz 	</li>
		<li>	Fundación Universitaria Luis Amigo 	</li>
		<li>	Fundación Centro Internacional de Educación y Desarrollo Humano - CINDE Universidad de Manizales 	</li>
		<li>	Instituto Nacional de Salud 	</li>
		<li>	Pontificia Universidad Javeriana 	</li>
		<li>	RENATA 	</li>
		<li>	SCARE, Sociedad Colombiana de Anestesiología y Reanimación 	</li>
		<li>	SENA, Servicio Nacional de Aprendizaje 	</li>
		<li>	Sociedad Colombiana de Física 	</li>
		<li>	Universidad Católica de Pereira 	</li>
		<li>	Universidad Distrital 	</li>
		<li>	Universidad EAFIT 	</li>
		<li>	Universidad EAN 	</li>
		<li>	Universidad Nacional de Colombia 	</li>
		<li>	Universidad Pedagógica y Tecnológica de Colombia UPTC 	</li>
		<li>	Universidad San Buenaventura 	</li>
		<li>	Universidad de Antioquia 	</li>
		<li>	Universidad de La Sabana 	</li>
		<li>	Universidad de los Andes 	</li>
		<li>	Universidad del Norte 	</li>
		<li>	Universidad del Rosario 	</li>
		<li>	Universidad del Tolima 	</li>
		<li>	Universidad del Valle 	</li>
	</ul>
		
	<h4><a name="Chile">Nodo Chile: Sistema de Información Científica –SIC-</a></h4>
	<br/>

	<p>O Sistema de Informação Científica – SIC – é um site que integra e centraliza os distintos serviços, plataformas e conteúdos do Programa de Informação Científica do CONICYT.</p>
	
	<h5>Links úteis</h5>
	<ul>
		<li><a href="http://www.sic.informacioncientifica.cl/">Sistema de Información Científica (SIC)</a></li>
		<li><a href="http://www.conicyt.cl/">CONICYT</a></li>		
	</ul>
	
	<h5>Instituições colhidas</h5>
	<ul>
		<li>	SciELO-Chile	</li>
		<li>	Repositorio Institucional	</li>
	</ul>
			
	<h4><a name="Ecuador">Nodo Ecuador:  Red de Repositorios Abiertos del Ecuador - RRAAE</a></h4>
	<br/>
	<p>La RRAAE es el buscador nacional, su propósito es facilitar la gestión, descentralización, organización, preservación e interoperabilidad de los contenidos digitales en  acceso abierto, que generan las instituciones de la comunidad académica - científica del país. Así fomentamos la visibilidad de la producción del conocimiento distribuido en los diferentes repositorios institucionales a nivel nacional, de este modo contribuimos al desarrollo de la educación en nuestro país.</p>
	<h5>Links úteis</h5>
	<ul>
		<li><a href="http://rraae.org.ec/">RRAAE</a></li>
		<li><a href="https://www.cedia.org.ec/">CEDIA</a></li>
		<li><a href="http://www.senescyt.gob.ec/">SENECYT</a></li>
	</ul>
	<h5>Instituições colhidas</h5>
	<ul>
		<li>Universidad de Cuenca</li>
		<li>Universidad Técnica del Norte</li>
		<li>Escuela Superior Politécnica del Litoral</li>
		<li>Universidad Central del Ecuador</li>
		<li>Escuela Superior Politécnica de Chimborazo</li>
		<li>Universidad de Guayaquil</li>
		<li>Universidad Politécnica Salesiana</li>
		<li>Universidad Técnica Particular de Loja</li>
		<li>Universidad del Azuay</li>
		<li>Universidad de las Fuerzas Armadas</li>
		<li>Universidad Estatal de Milagro</li>
		<li>Universidad Internacional del Ecuador</li>
		<li>Universidad Técnica de Ambato</li>
		<li>Universidad Estatal de Bolívar</li>
		<li>Universidad Tecnológica Equinoccial</li>
		<li>Universidad Regional Autónoma de los Andes</li>
		<li>Pontificia Universidad Católica del Ecuador</li>
		<li>Universidad Internacional del Ecuador</li>
		<li>Universidad Estatal Península de Santa Elena</li>
		<li>Universidad Nacional de Chimborazo</li>
		<li>Universidad Técnica de Machala</li>
		<li>Universidad de Otavalo</li>
		<li>Red Nacional de Investigación y Educación del Ecuador</li>
		<li>Secretaria de Ciencia, Tecnología e Innovación del Ecuador</li>
	</ul>
	
	<h4><a name="ElSalvador">Nodo El Salvador: Repositorio Digital de Ciencia y Cultura de El Salvador –REDICCES-</a></h4>
	<br/>
	<p>REDICCES busca ser uma ferramenta que ajuda a difundir a história, a produção científica, cultural e patrimonial de El Salvador. Esta é uma iniciativa do Consórcio de Bibliotecas Universitárias de El Salvador – CBUES -.</p>

	<h5>Links úteis</h5>
	<ul>
		<li><a href="http://www.redicces.org.sv">REDICCES</a></li>
		<li><a href="http://www.cbues.org.sv/ ">CBUES</a></li>
	
	</ul>
	
	<h5>Instituições colhidas</h5>
	<ul>
		<li>	Biblioteca Nacional de El Salvador Francisco Gavidia	</li>
		<li>	Consorcio de Bibliotecas Universitarias de El Salvador	</li>
		<li>	Consejo Nacional de Ciencia y Tecnología	</li>
		<li>	Escuela Superior de Economía y Negocios	</li>
		<li>	Escuela Especializada en Ingeniería	</li>
		<li>	Universidad Centroamericana "José Simeón Cañas"	</li>
		<li>	Universidad Don Bosco	</li>
		<li>	Universidad Dr. José Matías Delgado	</li>
		<li>	Universidad Evangélica de El Salvador	</li>
		<li>	Universidad de El Salvador	</li>
		<li>	Universidad Francisco Gavidia	</li>
		<li>	Universidad Tecnológica de El Salvador	</li>
	</ul>
	
	<h4><a name="Mexico">Nodo México: Red Mexicana de Repositorios Institucionales –REMERI-</a></h4>
	<br/>
	
	<p>REMERI tem por objetivo criar uma rede interconectada de repositórios digitais de instituições de educação superior (IES) no México, com a finalidade de integrar, difundir, preservar e dar visibilidade a sua produção científica, acadêmica e documental, assim como também incorporar-se a redes ou diretórios de repositórios internacionais para fomentar a colaboração e apoiar o acesso e a divulgação de conteúdos de acesso aberto.</p>
	<p>REMERI é um projeto desenvolvido por instituições participantes da Comunidade de Bibliotecas Digitais de CUDI e da Rede Aberta de Bibliotecas Digitais – RABID -, com o financiamento de Conselho Nacional de Ciência e Tecnologia - CONACYT-.</p>
	<h5>Links úteis</h5>
	<ul>
		<li><a href="http://www.remeri.org.mx/portal/index.html">REMERI</a></li>
		<li><a href="http://www.cudi.mx/ ">CUDI</a></li>
		<li><a href="http://www.conacyt.gob.mx/ ">CONACYT</a></li>	
	</ul>
	
	<h5>Instituições colhidas</h5>
	<ul>
		<li>	Benemérita Universidad Autónoma de Puebla (BUAP) 	</li>
		<li>	Centro de Investigación Científica y de Educación Superior de Ensenada Baja California (CICESE) 	</li>
		<li>	Centro de Investigación en Matemáticas (CIMAT) 	</li>
		<li>	Centro de Investigación y Docencia Económicas, A.C. (CIDE) 	</li>
		<li>	Colegio de Postgraduados (COLPOS) 	</li>
		<li>	Colegio de la Frontera Norte (COLEF) 	</li>
		<li>	FLACSO México (FLACSO) 	</li>
		<li>	Instituto Politécnico Nacional (IPN) 	</li>
		<li>	Instituto Tecnológico y de Estudios Superiores de Occidente (ITESO) 	</li>
		<li>	Instituto de Tecnológico de Estudios Superiores de Monterrey (ITESM) 	</li>
		<li>	Universidad Autónoma Metropolitana (UAM) 	</li>
		<li>	Universidad Autónoma de Aguascalientes (UAA) 	</li>
		<li>	Universidad Autónoma de Hidalgo (UAEH) 	</li>
		<li>	Universidad Autónoma de Nuevo León (UANL) 	</li>
		<li>	Universidad Autónoma de San Luis Potosí (UASLP) 	</li>
		<li>	Universidad Autónoma del Estado de México (UAEMEX) 	</li>
		<li>	Universidad Iberoamericana (UIA) 	</li>
		<li>	Universidad Michoacana de San Nicolás de Hidalgo (UMICH) 	</li>
		<li>	Universidad Nacional Autónoma de México (UNAM) 	</li>
		<li>	Universidad Veracruzana (UV) 	</li>
		<li>	Universidad de Guadalajara (UDG) 	</li>
		<li>	Universidad de las Américas Puebla (UDLAP) 	</li>
	</ul>
	

	<h4><a name="Peru">Nodo Perú: Acceso Libre a Información Científica para la Innovación</a></h4>
	<br/>
	<p>O Repositório Nacional Digital de Ciência, Tecnologia e Inovação de Acesso Aberto, denominado ALICIA (Acesso Livre à Informação Científica para a Inovação), é administrado pelo Conselho Nacional de Ciência, Tecnologia e Inovação Tecnológica (CONCYTEC) com o propósito de formar uma rede nacional interoperável de repositórios digitais, a partir do estabelecimento de políticas, padrões e protocolos comuns a todos os integrantes da Rede.</p>
	<h5>Links úteis</h5>
	<ul>
		<li><a href="http://alicia.concytec.gob.pe/alicia/">ALICIA</a></li>
	</ul>
	<h5>Instituições colhidas</h5>
	<ul>
		<li>	Universidad Nacional Mayor de San Marcos	</li>
		<li>	Universidad Nacional Agraria La Molina	</li>
		<li>	Universidad Nacional José Faustino Sánchez Carrión	</li>
		<li>	Universidad Nacional de Trujillo	</li>
		<li>	Universidad Peruana Cayetano Heredia	</li>
		<li>	Pontificia Universidad Católica del Perú	</li>
		<li>	Universidad Peruana de Ciencias Aplicadas	</li>
		<li>	Universidad Privada del Norte	</li>
		<li>	Universidad de Piura	</li>
		<li>	Universidad Alas Peruanas	</li>
		<li>	Universidad Católica Los Ángeles de Chimbote	</li>
		<li>	Universidad Ricardo Palma	</li>
		<li>	Universidad Señor de Sipan	</li>
		<li>	Universidad San Luis Gonzaga de Ica	</li>
		<li>	Universidad San Ignacio de Loyola	</li>
		<li>	Universidad del Chiclayo	</li>
		<li>	Universidad San Antonio Abad del Cusco	</li>
		<li>	Universidad del Pacífico	</li>
		<li>	Instituto del Mar del Perú, IMARPE	</li>
		<li>	Instituto Peruano de Energía Nuclear, IPEN	</li>
		<li>	Instituto Geológico Minero y Metalúrgico, INGEMMET	</li>
		<li>	Consejo Nacional de Ciencia, Tecnología e Innovación Tecnológica, CONCYTEC	</li>
	</ul>
		
	</div>
</div>  


<!-- /.row -->