<style>
h4 {
margin-bottom: 0px;
margin-top: 30px;

}

h5 {
font-size: 15px;
font-weight: bold;
}

p {
	text-align: justify;
}

#static-content li {
margin-bottom: 0px;
}
</style>

<div class="row"><br/></div>
   
<h2>Nodos nacionales</h2>
	
<div class="row"><br/>

	<div class="col-lg-11">
	    
	<p>Los nodos nacionales constituyen las redes de repositorios impulsadas entre los países miembros, por medio de iniciativas adaptadas a cada contexto. Siguiendo los estándares internacionales, técnicos y organizativos, las redes de cada país son el puente efectivo para integrar contenidos en el buscador de documentos científicos LA Referencia.</p>  
	
	<h4><a href="http://repositoriosdigitales.mincyt.gob.ar">Nodo Argentina: Sistema Nacional de Repositorios Digitales –SNRD-</a></h4>
	<a href="#Argentina">Leer resumen e instituciones</a>
	
	<h4><a href="http://oasisbr.ibict.br/">Nodo Brasil: Portal Brasileiro de Acesso Aberto à Informação Científica –oasisbr-</a></h4>
	<a href="#Brasil">Leer resumen e instituciones</a>
	
	<h4><a href="http://bdcol.org/">Nodo Colombia: Biblioteca Digital Colombiana –BDCOL-</a></h4>
	<a href="#Colombia">Leer resumen e instituciones</a>
	
	<h4><a href="http://www.sic.informacioncientifica.cl/">Nodo Chile: Sistema de Información Científica –SIC-</a></h4>
	<a href="#Chile">Leer resumen e instituciones</a>
	
	<h4><a href="http://repositorio.educacionsuperior.gob.ec/">Nodo Ecuador: Repositorio Digital –Senescyt-</a></h4>
	<a href="#Ecuador">Leer resumen e instituciones</a>
	
	<h4><a href="http://www.redicces.org.sv">Nodo El Salvador: Repositorio Digital de Ciencia y Cultura de El Salvador –REDICCES-</a></h4>
	<a href="#ElSalvador">Leer resumen e instituciones</a>
	
	<h4><a href="http://www.remeri.org.mx/portal/index.html">Nodo México: Red Mexicana de Repositorios Institucionales –REMERI-</a></h4>
	<a href="#Mexico">Leer resumen e instituciones</a>
	
	<h4><a href="http://alicia.concytec.gob.pe/alicia/">Nodo Perú: Acceso Libre a Información Científica para la Innovación</a></h4>
	<a href="#Peru">Leer resumen e instituciones</a>
	
	<h4><a href="#">Nodo Venezuela</a></h4>
	<a href="#Venezuela">Leer resumen e instituciones</a>
		
	</div>
</div>  

<br/><br/>
<h2>Detalle de las instituciones cosechadas</h2>

<div class="row">

	<div class="col-lg-11">
	    
	<h4><a name="Argentina">Nodo Argentina: Sistema Nacional de Repositorios Digitales –SNRD-</a></h4>
	<br/>
	<p>El SNRD promueve en Argentina el acceso abierto y el intercambio de la producción científico-tecnológica generada en ese país. Además, las instituciones adheridas pueden solicitar financiamiento para crear/fortalecer sus repositorios digitales y para la formación de recursos humanos.</p>
	<p>El SNRD tiene como propósito conformar una red interoperable de repositorios digitales en ciencia y tecnología en Argentina, a partir del establecimiento de políticas, estándares y protocolos comunes a todos los integrantes del Sistema.</p>
	<p>El SNRD cuenta con más de veinte mil documentos de doce repositorios argentinos. Esta es una iniciativa del Ministerio de Ciencia, Tecnología e Innovación Productiva conjuntamente con el Consejo Interinstitucional de Ciencia y Tecnología (CICyT) a través de sus representantes en el Consejo Asesor de la Biblioteca Electrónica de Ciencia y Tecnología.</p>

	<h5>Enlaces</h5>
	<ul>
		<li><a href="http://repositoriosdigitales.mincyt.gob.ar">SNRD</a></li>
		<li><a href="http://www.mincyt.gob.ar/">Ministerio de Ciencia, Tecnología e Innovación Productiva</a></li>
		<li><a href="http://www.cicyt.mincyt.gob.ar/">Consejo Interinstitucional de Ciencia y Tecnología (CICyT)</a></li>
		<li><a href="http://www.biblioteca.mincyt.gov.ar/">Biblioteca Electrónica de Ciencia y Tecnología</a></li>		
	</ul>
	
	<h5>Instituciones cosechadas</h5>
	<ul>
		<li>	Universidad de la Fraternidad de Agrupaciones Santo Tomás de Aquino (UFASTA)	</li>
		<li>	Universidad Nacional de Buenos Aires. Facultad de Ciencias Exactas y Naturales (UBA-FCEN)	</li>
		<li>	Universidad Nacional de La Plata (UNLP)	</li>
		<li>	Universidad Nacional de La Plata. Facultad de Humanidades y Ciencias de la Educación (UNLP-FAHCE)	</li>
		<li>	Universidad Nacional de Lanús (UNLA)	</li>
		<li>	Universidad Nacional de Mar del Plata. Facultad de Ciencias Económicas y Sociales (UNMdP. FCEyS)	</li>
		<li>	Universidad Nacional del Litoral (UNL)	</li>
	</ul>
	
	
	<h4><a name="Brasil">Nodo Brasil: Portal Brasileiro de Acesso Aberto à Informação Científica –oasisbr-</a></h4>
	<br/>
	<p>O Portal Brasileiro de Acesso Aberto à Informação Científica – oasisbr- é um mecanismo de busca multidisciplinar que permite o acesso gratuito à produção científica de autores vinculados a universidades e institutos de pesquisa brasileiros.</p> 	
	<p>Oasisbr é um dos resultados dos esforços do Ibict, apoiados pela Financiadora de Estudos e Projetos - FINEP, para a inserção da ciência brasileira do contexto acesso aberto à informação científica.</p>

	<h5>Enlaces</h5>
	<ul>
		<li><a href="http://oasis.ibict.br/ ">Portal Brasileiro de Acesso Aberto à Informação Científica – oasisbr</a></li>
		<li><a href="http://www.ibict.br/">Ibict</a></li>
		<li><a href="http://www.finep.gov.br/ ">Financiadora de Estudos e Projetos - FINEP</a></li>
	</ul>
	
	<h5>Instituciones cosechadas</h5>
	<ul>
		<li>	Universidade Aberta do SUS	</li>
		<li>	Universidade Metodista de Sao Paulo	</li>
		<li>	Universidade Municipal de São Caetano do Sul	</li>
		<li>	Instituto Brasileiro de Informação em Ciência e Tecnologia	</li>
		<li>	Fundação Centro Tecnológico de Minas Gerais (Portugal)	</li>
		<li>	Universidade Federal de Pelotas	</li>
		<li>	Empresa Brasileira de Pesquisa Agropecuária	</li>
		<li>	Universidade Federal do Rio Grande do Sul	</li>
		<li>	Universidade Federal Fluminense	</li>
		<li>	Museu Paraense Emílio Goeldi	</li>
		<li>	Universidade Federal do Rio Grando do Norte	</li>
		<li>	Universidade de São Paulo	</li>
		<li>	Universidade Federal de Viçosa	</li>
		<li>	Universidade Tecnológica Federal do Paraná	</li>
		<li>	Centro de Tecnologia da Informação Renato Archier	</li>
		<li>	Fundação Centro Tecnológico de Minas Gerais (CETEC)	</li>
		<li>	Instituto Nacional de Tecnologia	</li>
		<li>	Universidade Federal de Grande Dourados	</li>
		<li>	Universidade Federal do Maranhão	</li>
		<li>	Universidade de Brasília	</li>
		<li>	SciELO Brasil-Bireme	</li>
		<li>	Universidade Estadual de Ponta Grossa	</li>
	</ul>
	
	<h4><a name="Colombia">Nodo Colombia: Biblioteca Digital Colombiana –BDCOL-</a></h4>
	<br/>

	<p>BDCOL surge en el año 2007 como una iniciativa de las instituciones de educación superior en Colombia para promover el acceso al conocimiento que se genera en ese país. El Departamento Administrativo de Ciencia, Tecnología e Innovación de COLCIENCIAS, el Ministerio de Educación Nacional y la Red Nacional Académica de Tecnología Avanzada –RENATA- han querido fortalecer esta la iniciativa de repositorios en Colombia, por medio de una Estrategia Nacional de Acceso Abierto al Conocimiento, canalizada por BDCOL. </p>
	
	<h5>Enlaces</h5>
	<ul>
		<li><a href="http://bdcol.org/">BDCOL</a></li>
		<li><a href="http://www.colciencias.gov.co/">COLCIENCIAS</a></li>
		<li><a href="http://www.mineducacion.gov.co/">Ministerio de Educación Nacional</a></li>
		<li><a href="http://www.renata.edu.co/ ">RENATA</a></li>
		
	</ul>
	
	<h5>Instituciones cosechadas</h5>
	<ul>
		<li>	ACFO, Asociación Colombiana de Facultades de Odontología 	</li>
		<li>	ACTA, Asociación Colombiana de Ciencia y Tecnología de Alimentos 	</li>
		<li>	Fundación Universitaria Konrad Lorenz 	</li>
		<li>	Fundación Universitaria Luis Amigo 	</li>
		<li>	Fundación Centro Internacional de Educación y Desarrollo Humano - CINDE Universidad de Manizales 	</li>
		<li>	Instituto Nacional de Salud 	</li>
		<li>	Pontificia Universidad Javeriana 	</li>
		<li>	RENATA 	</li>
		<li>	SCARE, Sociedad Colombiana de Anestesiología y Reanimación 	</li>
		<li>	SENA, Servicio Nacional de Aprendizaje 	</li>
		<li>	Sociedad Colombiana de Física 	</li>
		<li>	Universidad Católica de Pereira 	</li>
		<li>	Universidad Distrital 	</li>
		<li>	Universidad EAFIT 	</li>
		<li>	Universidad EAN 	</li>
		<li>	Universidad Nacional de Colombia 	</li>
		<li>	Universidad Pedagógica y Tecnológica de Colombia UPTC 	</li>
		<li>	Universidad San Buenaventura 	</li>
		<li>	Universidad de Antioquia 	</li>
		<li>	Universidad de La Sabana 	</li>
		<li>	Universidad de los Andes 	</li>
		<li>	Universidad del Norte 	</li>
		<li>	Universidad del Rosario 	</li>
		<li>	Universidad del Tolima 	</li>
		<li>	Universidad del Valle 	</li>
	</ul>
		
	<h4><a name="Chile">Nodo Chile: Sistema de Información Científica –SIC-</a></h4>
	<br/>

	<p>El Sistema de Información Científica –SIC- es un sitio web que integra y centraliza los distintos servicios, plataformas y contenidos del Programa de Información Científica de CONICYT.</p>
	
	<h5>Enlaces</h5>
	<ul>
		<li><a href="http://www.sic.informacioncientifica.cl/">Sistema de Información Científica (SIC)</a></li>
		<li><a href="http://www.conicyt.cl/">CONICYT</a></li>		
	</ul>
	
	<h5>Instituciones cosechadas</h5>
	<ul>
		<li>	Biblioteca Electrónica de Información Científica, BEIC	</li>
		<li>	SciELO-Chile	</li>
		<li>	Repositorio Institucional	</li>
		<li>	Portal del Investigador	</li>
		<li>	Portal de Productividad	</li>
	</ul>
			
	<h4><a name="Ecuador">Nodo Ecuador: Repositorio Digital –Senescyt-</a></h4>
	<br/>
	<p>Repositorio de Educación de Ecuador</p>
	<h5>Enlaces</h5>
	<ul>
		<li><a href="http://repositorio.educacionsuperior.gob.ec/">Repositorio de Educación de Ecuador</a></li>
	</ul>
	
	<h4><a name="ElSalvador">Nodo El Salvador: Repositorio Digital de Ciencia y Cultura de El Salvador –REDICCES-</a></h4>
	<br/>
	<p>REDICCES busca ser una herramienta que ayude a difundir la historia, producción científica, cultural y patrimonial de El Salvador. Esta es una iniciativa del Consorcio de Bibliotecas Universitarias de El Salvador -CBUES-</p>

	<h5>Enlaces</h5>
	<ul>
		<li><a href="http://www.redicces.org.sv">REDICCES</a></li>
		<li><a href="http://www.cbues.org.sv/ ">CBUES</a></li>
	
	</ul>
	
	<h5>Instituciones cosechadas</h5>
	<ul>
		<li>	Biblioteca Nacional de El Salvador Francisco Gavidia	</li>
		<li>	Consorcio de Bibliotecas Universitarias de El Salvador	</li>
		<li>	Consejo Nacional de Ciencia y Tecnología	</li>
		<li>	Escuela Superior de Economía y Negocios	</li>
		<li>	Escuela Especializada en Ingeniería	</li>
		<li>	Universidad Centroamericana "José Simeón Cañas"	</li>
		<li>	Universidad Don Bosco	</li>
		<li>	Universidad Dr. José Matías Delgado	</li>
		<li>	Universidad Evangélica de El Salvador	</li>
		<li>	Universidad de El Salvador	</li>
		<li>	Universidad Francisco Gavidia	</li>
		<li>	Universidad Tecnológica de El Salvador	</li>
	</ul>
	
	<h4><a name="Mexico">Nodo México: Red Mexicana de Repositorios Institucionales –REMERI-</a></h4>
	<br/>
	
	<p>REMERI tiene por objeto crear una red interconectada de repositorios digitales de instituciones de educación superior (IES) en México, con la finalidad de integrar, difundir, preservar y dar visibilidad a su producción científica, académica y documental, así como también, incorporarse a redes o directorios de repositorios internacionales para fomentar la colaboración y apoyar el acceso y la divulgación de contenidos de acceso abierto.</p>
	<p>REMERI es un proyecto desarrollado por instituciones participantes en la Comunidad de Bibliotecas Digitales de CUDI y de la Red Abierta de Bibliotecas Digitales –RABID-, con el financiamiento del Consejo Nacional de Ciencia y Tecnología –CONACYT-.</p>
	<h5>Enlaces</h5>
	<ul>
		<li><a href="http://www.remeri.org.mx/portal/index.html">REMERI</a></li>
		<li><a href="http://www.cudi.mx/ ">CUDI</a></li>
		<li><a href="http://www.rabid.org.mx/">RABID</a></li>
		<li><a href="http://www.conacyt.gob.mx/ ">CONACYT</a></li>	
	</ul>
	
	<h5>Instituciones cosechadas</h5>
	<ul>
		<li>	Benemérita Universidad Autónoma de Puebla (BUAP) 	</li>
		<li>	Centro de Investigación Científica y de Educación Superior de Ensenada Baja California (CICESE) 	</li>
		<li>	Centro de Investigación en Matemáticas (CIMAT) 	</li>
		<li>	Centro de Investigación y Docencia Económicas, A.C. (CIDE) 	</li>
		<li>	Colegio de Postgraduados (COLPOS) 	</li>
		<li>	Colegio de la Frontera Norte (COLEF) 	</li>
		<li>	FLACSO México (FLACSO) 	</li>
		<li>	Instituto Politécnico Nacional (IPN) 	</li>
		<li>	Instituto Tecnológico y de Estudios Superiores de Occidente (ITESO) 	</li>
		<li>	Instituto de Tecnológico de Estudios Superiores de Monterrey (ITESM) 	</li>
		<li>	Universidad Autónoma Metropolitana (UAM) 	</li>
		<li>	Universidad Autónoma de Aguascalientes (UAA) 	</li>
		<li>	Universidad Autónoma de Hidalgo (UAEH) 	</li>
		<li>	Universidad Autónoma de Nuevo León (UANL) 	</li>
		<li>	Universidad Autónoma de San Luis Potosí (UASLP) 	</li>
		<li>	Universidad Autónoma del Estado de México (UAEMEX) 	</li>
		<li>	Universidad Iberoamericana (UIA) 	</li>
		<li>	Universidad Michoacana de San Nicolás de Hidalgo (UMICH) 	</li>
		<li>	Universidad Nacional Autónoma de México (UNAM) 	</li>
		<li>	Universidad Veracruzana (UV) 	</li>
		<li>	Universidad de Guadalajara (UDG) 	</li>
		<li>	Universidad de las Américas Puebla (UDLAP) 	</li>
	</ul>
	

	<h4><a name="Peru">Nodo Perú: Acceso Libre a Información Científica para la Innovación</a></h4>
	<br/>
	<p>El Repositorio Nacional Digital de Ciencia, Tecnología e Innovación de Acceso Abierto denominado ALICIA (Acceso Libre a Información Científica para la Innovación), es administrado por el Consejo Nacional de Ciencia, Tecnología e Innovación Tecnológica (CONCYTEC) con el propósito de conformar una red nacional interoperable de repositorios digitales, a partir del establecimiento de políticas, estándares y protocolos comunes a todos los integrantes de la Red. </p>
	<h5>Enlaces</h5>
	<ul>
		<li><a href="http://alicia.concytec.gob.pe/alicia/">ALICIA</a></li>
	</ul>
	<h5>Instituciones cosechadas</h5>
	<ul>
		<li>	Universidad Nacional Mayor de San Marcos	</li>
		<li>	Universidad Nacional Agraria La Molina	</li>
		<li>	Universidad Nacional José Faustino Sánchez Carrión	</li>
		<li>	Universidad Nacional de Trujillo	</li>
		<li>	Universidad Peruana Cayetano Heredia	</li>
		<li>	Pontificia Universidad Católica del Perú	</li>
		<li>	Universidad Peruana de Ciencias Aplicadas	</li>
		<li>	Universidad Privada del Norte	</li>
		<li>	Universidad de Piura	</li>
		<li>	Universidad Alas Peruanas	</li>
		<li>	Universidad Católica Los Ángeles de Chimbote	</li>
		<li>	Universidad Ricardo Palma	</li>
		<li>	Universidad Señor de Sipan	</li>
		<li>	Universidad San Luis Gonzaga de Ica	</li>
		<li>	Universidad San Ignacio de Loyola	</li>
		<li>	Universidad del Chiclayo	</li>
		<li>	Universidad San Antonio Abad del Cusco	</li>
		<li>	Universidad del Pacífico	</li>
		<li>	Instituto del Mar del Perú, IMARPE	</li>
		<li>	Instituto Peruano de Energía Nuclear, IPEN	</li>
		<li>	Instituto Geológico Minero y Metalúrgico, INGEMMET	</li>
		<li>	Consejo Nacional de Ciencia, Tecnología e Innovación Tecnológica, CONCYTEC	</li>
	</ul>
		
	</div>
</div>  


<!-- /.row -->