

<div class="row"><br/></div>
   
<h2>Tecnología – Desarrollo de software</h2>
	
<div class="row"><br/>
            
	<div class="col-lg-11">
	
	<p>LA Referencia  opera enteramente sobre una plataforma de software libre  (GPL 3)  desarrollada inicialmente como un piloto en el proyecto liderado por  <a href="http://www.redclara.net/index.php/conocimiento-e-innovacion/articulacion/finalizados/bid-brp-repositorios-institucionales">RedCLARA</a> con financiamiento del   <a href="http://www.iadb.org/es/proyectos/project-information-page,1303.html?id=rg-t1684">BID</a>  y asociados.</p>

	<p>Desde fines del 2013 es mantenida y actualizada por el equipo de LA Referencia y validada por la comunidad de usuarios mediante reuniones técnicas periódicas del Comité Técnico de los países miembros.</p>
	
	<p>La plataforma está integrada por tres componentes que funcionan coordinados:</p>
	
	<ul>
	
	<li><b>LRHarvester:</b> componente de cosecha, transformación y validación de metadatos OAI-PMH. Responsable de la cosecha de fuentes OAI, validación de registros de metadatos y su  transformación para el cumplimiento de las directrices de calidad de LA Referencia. El componente de cosecha se basó  inicialmente en OCLCHarvester2.</li>
	
	<li><b>LRProvider:</b> componente responsable de la publicación de metadatos mediante el protocolo OAI-PMH, actualmente derivado del software Dspace-XOAI, que ofrece una alta flexibilidad y escalabilidad para la interoperabilidad con otros agregadores internacionales de metadatos.</li>
	
	<li><b>Buscador/Portal de servicios:</b> componente de publicación de los metadatos agregados que ofrece un interfaz de búsqueda amigable y adaptativa para dispositivos móviles. Además brinda estadísticas sobre calidad de metadatos y evolución de las cosechas. Este componente está basado en el software libre Vufind (http://vufind.org) sobre el que se han desarrollado módulos específicos.</li>
	
	</ul>
	
	<p>La plataforma está desarrollada en lenguaje Java 1.7, utilizando el framework Spring  y el motor de base de datos PostgreSQL 9.X. También funciona sobre MySQL.</p>
	
	<p>Además de soportar el  nodo central LA Referencia, la plataforma funciona como agregador y portal nacional para los países miembros.</p> 

	<p>Actualmente está instalada en los siguientes países:</p>     
	
	<ul>
		<li><b>Brasil (IBICT)</b><a target="_blank" href="http://oasisbr.ibict.br/vufind/"><img src="/vufind/themes/bootstrap3lr/images/nodes/oasis.jpg"/></a></li>
		<li><b>Ecuador (CEDIA/SENECYT)</b><a target="_blank" href="http://rraae.org.ec/">&nbsp;&nbsp;<img width="80" height="29" src="/vufind/themes/bootstrap3lr/images/nodes/rraae.png"/></a></li>
		<li><b>Perú (CONCYTEC)</b><a target="_blank" href="http://alicia.concytec.gob.pe/vufind/"><img src="/vufind/themes/bootstrap3lr/images/nodes/alicia.jpg"/></a></li>
	</ul>        
	             
	<p>El componente agregador (LRHarvester y LRProvider) entrega los servicios del nodo de CONICYT-Chile y  de  Renata-Colombia.<p>

	<p>El software y documentación están disponibles en el repositorio GITHUB <a href="https://github.com/lareferencia">https://github.com/lareferencia</a><p>
	             
	             
    </div>
</div>                
<!-- /.row -->