

<div class="row"><br/></div>
   
<h2>Tecnologia – Desenvolvimento de software</h2>
	
<div class="row"><br/>
            
	<div class="col-lg-11">
	
	<p>LA Referencia opera inteiramente sobre uma plataforma de software livre  (GPL 3)  desenvolvida inicialmente como um piloto no projeto liderado por <a href="http://www.redclara.net/index.php/conocimiento-e-innovacion/articulacion/finalizados/bid-brp-repositorios-institucionales">RedCLARA</a> com financiamento do  <a href="http://www.iadb.org/es/proyectos/project-information-page,1303.html?id=rg-t1684">BID</a>  e associados.</p>

	<p>Desde o fim de 2013 é mantida e atualizada pela equipe de LA Referencia e validada pela comunidade de usuários mediante reuniões técnicas periódicas do Comitê Técnico dos países membros.</p>
	
	<p>A plataforma está integrada por três componentes que funcionam coordenados:</p>
	
	<ul>
	
	<li><b>LRHarvester:</b> componente de colheita, transformação e validação de metadados OAI-PMH. Responsável pela colheita de fontes OAI, validação de registros de metadados e sua transformação para o cumprimento das diretrizes de qualidade de LA Referencia. O componente de colheita se baseou inicialmente em OCLCHarvester2.</li>
	
	<li><b>LRProvider:</b> componente responsável pela publicação de metadados mediante o protocolo OAI-PMH, atualmente derivado do software Dspace-XOAI, que oferece uma alta flexibilidade e escalabilidade para a interoperabilidade com outros agregadores internacionais de metadados.</li>
	
	<li><b>Buscador/Portal de serviços:</b> componente de publicação dos metadados agregados que oferece uma interface de busca amigável e adaptativa para dispositivos móveis. Além disso, oferece estatísticas sobre qualidade de metadados e evolução das colheitas. Este componente está baseado no software libre Vufind (http://vufind.org) sobre o qual foram desenvolvidos módulos específicos.</li>
	
	</ul>
	
	<p>A plataforma está desenvolvida em linguagem Java 1.7, utilizando o framework Spring e o motor de base de dados PostgreSQL 9.X. Também funciona sobre MySQL.</p>
	
	<p>Além de suportar o nodo central LA Referencia, a plataforma funciona como agregador e portal nacional para os países membros.</p> 

	<p>Atualmente está instalada nos seguintes países:</p>     
	
	<ul>
		<li><b>Brasil (IBICT)</b><a target="_blank" href="http://oasisbr.ibict.br/vufind/"><img src="/vufind/themes/bootstrap3lr/images/nodes/oasis.jpg"/></a></li>
		<li><b>Equador (CEDIA/SENECYT)</b><a target="_blank" href="http://rraae.org.ec/">&nbsp;&nbsp;<img width="80" height="29" src="/vufind/themes/bootstrap3lr/images/nodes/rraae.png"/></a></li>
		<li><b>Peru (CONCYTEC)</b><a target="_blank" href="http://alicia.concytec.gob.pe/vufind/"><img src="/vufind/themes/bootstrap3lr/images/nodes/alicia.jpg"/></a></li>
	</ul>        
	             
	<p>O componente agregador (LRHarvester e LRProvider) entrega os serviços do nodo de CONICYT-Chile e de RENATA-Colômbia.<p>

	<p>O software e a documentação estão disponíveis no repositório GITHUB <a href="https://github.com/lareferencia">https://github.com/lareferencia</a><p>
	             
	             
    </div>
</div>                
<!-- /.row -->
