

<div class="row"><br/></div>
   
<h2>¿Qué es el buscador regional LA Referencia?</h2>
	
<div class="row"><br/>
            
	<div class="col-lg-11">
    
	   <p>El buscador regional LA Referencia es un servicio que apoya las estrategias nacionales de Acceso Abierto en América Latina mediante una plataforma con estándares de interoperabilidad. A partir de nodos nacionales, se integran artículos científicos, tesis doctorales y de maestría, provenientes de casi un centenar de universidades e instituciones de investigación. Esta experiencia se basa en acuerdos técnicos y organizativos entre organismos públicos de ciencia y tecnología (Ministerios y Oncyts) de los países miembros, conjuntamente con RedCLARA.</p>
             
    </div>
</div>                
<!-- /.row -->