

<div class="row"><br/></div>
   
<h2>¿Quiénes participan?</h2>
	
<div class="row"><br/>
            
	<div class="col-lg-11">
	
	
	<p>Los países y redes nacionales en permanente construcción participan en LA Referencia con grandes expectativas de seguir creciendo en la región. Así, han alcanzado acuerdos políticos, técnicos y organizativos para materializar una red  regional de repositorios que mejora continuamente sus procesos y que derivó  en el  buscador de publicaciones científicas, entre otros servicios.

	
	<h4>Países</h4>
	
	<p>Desde el inicio han participado Argentina, Brasil, Chile, Colombia, Ecuador, México, Perú y Venezuela. El Salvador se incorporó en la segunda mitad de la primera etapa. Estos países han ido organizándose internamente en nodos nacionales (enlazar a la página de nodos nacionales), incluyendo a su vez decenas de universidades y centros de investigación.
LA Referencia planifica la incorporación de otros países de la región, mediante acuerdos consensuados.</p>

	<h4>Instituciones socias:</h4>
	
   <p>LA Referencia es posible gracias a las instituciones socias, representantes de cada país, apoyo y enlace de gran peso con los contextos nacionales:</p>

   <ul>
   <li><a href="http://www.redclara.net/">RedCLARA</a></li> 
    <li><a href="http://www.mincyt.gob.ar/">Ministerio de Ciencia, Tecnología e Innovación Productiva de Argentina</a></li> 
    <li><a href="http://www.ibict.br/">IBICT Brasil</a></li> 
    <li><a href="http://www.conicyt.cl/">Comisión Nacional de Investigación y Tecnología de Chile</a></li> 
    <li><a href="http://www.mineducacion.gov.co/1621/w3-channel.html">Ministerio de Educación de Colombia</a></li> 
    <li><a href="http://www.colciencias.gov.co/ ">Colciencias Colombia</a></li> 
    <li><a href="http://www.educacionsuperior.gob.ec/">Secretaría de Educación Superior, Ciencia, Tecnología e Innovación de Ecuador</a></li> 
    
    <li><a href="http://www.conacyt.mx/">Consejo Nacional de Ciencia y Tecnología de México</a></li> 
    <li><a href="http://portal.concytec.gob.pe/">Consejo Nacional de Ciencia, Tecnología e Innovación Tecnológica de Perú</a></li> 
    <li><a href="http://www.cienciaytecnologia.edu.sv/">Viceministerio de Ciencia y Tecnología de El Salvador</a></li> 
       
</ul>	
	
	

	           
             
    </div>
</div>                
<!-- /.row -->