

<div class="row"><br/></div>
   
<h2>¿Quiénes participan?</h2>
	
<div class="row"><br/>
            
	<div class="col-lg-11">
	
	
	<p>Los países y redes nacionales participan en LA Referencia mediante acuerdos políticos, técnicos y organizativos para materializar una red regional de repositorios que mejora continuamente sus procesos y que derivó en el buscador de publicaciones científicas, entre otros servicios.</p>

	
	<h4>Países</h4>
	
	<p>Desde el inicio participaron  Argentina, Brasil, Chile, Colombia, Ecuador, México, Perú.  El Salvador se incorporó en la segunda mitad de la primera etapa y Costa Rica el 2016. Estos países se han organizado en nodos nacionales (enlazar a la página de nodos nacionales), incluyendo a su vez cientos de universidades y centros de investigación. </p>

	<h4>Instituciones socias:</h4>
	
   <p>LA Referencia es posible gracias a las instituciones socias, representantes de cada país, apoyo y enlace de gran peso con los contextos nacionales:</p>

   <ul>
   <li><a href="http://www.redclara.net/">RedCLARA</a></li> 
    <li><a href="http://www.mincyt.gob.ar/">Ministerio de Ciencia, Tecnología e Innovación Productiva. MINCYT, Argentina</a></li> 
    <li><a href="http://www.ibict.br/">Instituto Brasileiro de Informação em Ciência e Tecnologia. IBICT,  Brasil</a></li> 
    <li><a href="http://www.conicyt.cl/">Comisión Nacional de Investigación Científica y Tecnológica. Conicyt, Chile</a></li> 
    <li><a href="http://www.mineducacion.gov.co/1621/w3-channel.html">Ministerio de Educación, Colombia</a></li> 
    <li><a href="http://www.colciencias.gov.co/ ">Colciencias, Colombia</a></li> 
    <li><a href="https://www.conare.ac.cr/">Conare y Ministerio de Ciencia, Tecnología y Telecomunicaciones. Costa Rica </a></li> 

    <li><a href="http://www.educacionsuperior.gob.ec/">Secretaría de Educación Superior, Ciencia, Tecnología e Innovación. Senescyt, Ecuador </a></li> 
    <li><a href="http://www.cienciaytecnologia.edu.sv/">Ministerio de Educación. Viceministerio de Ciencia y Tecnología, El Salvador</a></li> 
    
    <li><a href="http://www.conacyt.mx/">Consejo Nacional de Ciencia y Tecnología. Conacyt, México</a></li> 
    <li><a href="http://portal.concytec.gob.pe/">Consejo Nacional de Ciencia, Tecnología e Innovación Tecnológica. Concytec, Perú</a></li> 
       
</ul>	  
	
	

	           
             
    </div>
</div>                
<!-- /.row -->