

<div class="row"><br/></div>
   
<h2>Quem participa?</h2>
	
<div class="row"><br/>
            
	<div class="col-lg-11">
	
	
	<p>Os países e redes nacionais em permanente construção participam de LA Referencia com grandes expectativas de seguir crescendo na região. Assim, chegaram a acordos políticos, técnicos e organizativos para materializar uma rede regional de repositórios que melhora continuamente seus processos e que resultou no buscador de publicações científicas, entre outros serviços.</p>

	
	<h4>Países</h4>
	
	<p>Desde o início participaram Argentina, Brasil, Chile, Colômbia, Equador, México, Peru e Venezuela. El Salvador se incorporou na segunda metade da primeira etapa. Estes países foram se organizando internamente em nodos nacionais, incluindo, por sua vez, a dezenas de universidades e centros de pesquisa. LA Referencia planeja a incorporação de outros países da região, mediante acordos consensuais.</p>

	<h4>Instituições sócias:</h4>
	
   <p>LA Referencia só é possível graças às instituições sócias, representantes de cada país, apoio e conexão de grande peso com os contextos nacionais. </p>

   <ul>
   <li><a href="http://www.redclara.net/">RedCLARA</a></li> 
    <li><a href="http://www.mincyt.gob.ar/">Ministerio de Ciencia, Tecnología e Innovación Productiva. MINCYT, Argentina</a></li> 
    <li><a href="http://www.ibict.br/">Instituto Brasileiro de Informação em Ciência e Tecnologia. IBICT,  Brasil</a></li> 
    <li><a href="http://www.conicyt.cl/">Comisión Nacional de Investigación Científica y Tecnológica. Conicyt, Chile</a></li> 
    <li><a href="http://www.mineducacion.gov.co/1621/w3-channel.html">Ministerio de Educación, Colombia</a></li> 
    <li><a href="http://www.colciencias.gov.co/ ">Colciencias, Colombia</a></li> 
    <li><a href="https://www.conare.ac.cr/">Conare y Ministerio de Ciencia, Tecnología y Telecomunicaciones. Costa Rica </a></li> 

    <li><a href="http://www.educacionsuperior.gob.ec/">Secretaría de Educación Superior, Ciencia, Tecnología e Innovación. Senescyt, Ecuador </a></li> 
    <li><a href="http://www.cienciaytecnologia.edu.sv/">Ministerio de Educación. Viceministerio de Ciencia y Tecnología, El Salvador</a></li> 

    <li><a href="http://www.conacyt.mx/">Consejo Nacional de Ciencia y Tecnología. Conacyt, México</a></li> 
    <li><a href="http://portal.concytec.gob.pe/">Consejo Nacional de Ciencia, Tecnología e Innovación Tecnológica. Concytec, Perú</a></li> 

</ul> 
	
	

	           
             
    </div>
</div>                
<!-- /.row -->