

<div class="row"><br/></div>
   
<h2>¿Quiénes participan?</h2>
	
<div class="row"><br/>
            
	<div class="col-lg-11">
	
	
	<p>Nueve países, nueve redes nacionales y casi un centenar de instituciones se encuentran participando en LA Referencia, con grandes expectativas de seguir creciendo en la región.</p>

    <p>Durante la primera etapa de LA Referencia, los países miembros lograron acuerdos políticos, técnicos y organizativos para activar una experiencia regional de repositorios.</p>

	<p>Desde el inicio han participado Argentina, Brasil, Chile, Colombia, Ecuador, México, Perú y Venezuela. El Salvador se incorporó en la segunda mitad de la primera etapa. Estos países debieron organizarse internamente como nodos nacionales que agrupan a su vez diversos repositorios, principalmente de universidades.</p>

    <p>Puede revisar las redes nacionales e instituciones que integran el buscador de documentos científicos aquí.</p>
    
	           
             
    </div>
</div>                
<!-- /.row -->