<?
    // Set page title.
    $this->headTitle($this->translate('Statistics'));
    
    $this->headLink()->appendStylesheet('vendor/morris.css');
    $this->headLink()->appendStylesheet('vendor/dataTables.bootstrap.css');
    $this->headLink()->appendStylesheet('vendor/font-awesome.min.css');
    

    $this->headScript()->appendFile('vendor/morris/raphael.min.js');
    $this->headScript()->appendFile('vendor/morris/morris.min.js');

    $this->headScript()->appendFile('vendor/dataTables/jquery.dataTables.js');
    $this->headScript()->appendFile('vendor/dataTables/dataTables.bootstrap.js');    
?>


<div class="<?=$this->layoutClass('widebody')?>">
  <!--h2><?=$this->transEsc('Statistics')?></h2-->
  
   <?=json_encode($this->harvestingHistory) ?>
  
   <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4>Acceso a registros por red (mensual)</h4><!--i class="fa fa-bar-chart-o fa-fw"></i--> 
                            
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div id="networks-bar-chart"></div>
			    			<div class="row"><br/><br/></div>
			    			
			    			<div id="history-line-chart"></div>
			    			<div class="row"><br/><br/></div>
			    			
         		    		<div class="table-responsive">
                                <table  class="table table-striped table-bordered table-hover" id="clicks-datatable">
                                    <thead/>
                                    <tbody/>
                                </table>
                            </div>
			   			    <div class="row"><br/><br/></div>
                            <div class="well">
                                <h4>Sobre las estadísticas de acceso a registros</h4>
                                <p>DataTables is a very flexible, advanced tables plugin for jQuery. In SB Admin, we are using a specialized version of DataTables built for Bootstrap 3. We have also customized the table headings to use Font Awesome icons in place of images. For complete documentation on DataTables, visit their website at <a target="_blank" href="https://datatables.net/">https://datatables.net/</a>.</p>
                            </div>

                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-8 -->
            </div>
            <!-- /.row -->
     
</div>


<script type="text/javascript">

var rawJson =  <?=json_encode($this->data) ?>;
var data = rawJson.networks;

var historyJSON =  <?=json_encode($this->harvestingHistory) ?>;


Morris.Bar({
	  element: 'networks-bar-chart',
	  data: data,
	  xkey: 'name',
	  ykeys: ['size', 'validSize', 'transformedSize'],
	  labels: ['Total cosechado', 'Válidos', 'Transformados'],
	  stacked: true
	});


Morris.Line({
    element: 'history-line-chart',
    data: historyJSON,
    xkey: 'datestamp', 
    ykeys: ['size', 'validSize','transformedSize', ],
    labels: ['Size','Valid','Transformed'],
    xLabels: 'day',
    pointSize: 2,
    smoth: 'false',
    hideHover: false,
    resize: true
});


var columns = [];
columns.push({ 'data':'timestamp', 'title':'Período' });

$.each( sources, function( key, value ) {
        columns.push( {'data':key, 'title':key} );
}); 

$('#clicks-datatable').dataTable( {
    data: data,
    columns: columns,
    bFilter: false, 
    bInfo: false,
    bPaginate: false
} );   

</script>

<!--  div class="<?=$this->layoutClass('sidebar')?>">
  <?=$this->render("admin/menu.phtml")?>
</div-->
