<div class="headline">
		<h2>Noticias destacadas</h2>
</div>
<div class="row margin-bottom-20">
	<div class="col-md-4 col-sm-12">
		<div class="thumbnails thumbnail-style thumbnail-kenburn">
			<div class="thumbnail-img col-md-12 col-sm-6">
				<div class="overflow-hidden">
					<img class="img-responsive" src="<?=$this->imageLink('news/costa_rica.jpg')?>" alt="" />
				</div>
				<a target="_blank" class="btn-more hover-effect" href="http://lareferencia.redclara.net/rfr/noticias/costa-rica-nuevo-miembro-de-la-referencia">+ <?=$this->transEsc("read more")?></a>
			</div>
			<div class="caption col-md-12 col-sm-6">
				<h3>
					<a target="_blank" class="hover-effect" href="http://lareferencia.redclara.net/rfr/noticias/costa-rica-nuevo-miembro-de-la-referencia">Costa Rica: nuevo miembro de LA Referencia</a>
				</h3>
				<p>LA Referencia se complace en anunciar la incorporación de Costa Rica como nuevo país en condición de observador</p>
			</div>
		</div>
	</div>
	<div class="col-md-4 col-sm-12">
		<div class="thumbnails thumbnail-style thumbnail-kenburn ">
			<div class="thumbnail-img col-md-12 col-sm-6">
				<div class="overflow-hidden">
					<img class="img-responsive" src="<?=$this->imageLink('news/peru.jpg')?>" alt=""/>
				</div>
				<a target="_blank" class="btn-more hover-effect" href="http://lareferencia.redclara.net/rfr/noticias/peru-aprobo-reglamento-de-ley-en-repositorios-y-acceso-abierto">+ <?=$this->transEsc("read more")?></a>
			</div>
			<div class="caption col-md-12 col-sm-6">
				<h3>
					<a target="_blank" class="hover-effect" href="http://lareferencia.redclara.net/rfr/noticias/peru-aprobo-reglamento-de-ley-en-repositorios-y-acceso-abierto">Perú aprobó reglamento de Ley en Repositorios y Acceso Abierto</a>
				</h3>
				<p>LA Referencia felicita a Perú por la reciente aprobación del Reglamento de la Ley que regula el Repositorio Nacional Digital de Ciencia, Tecnología e Innovación de Acceso Abierto</p>
			</div>
		</div>
	</div>
	<div class="col-md-4 col-sm-12">
		<div class="thumbnails thumbnail-style thumbnail-kenburn ">
			<div class="thumbnail-img col-md-12 col-sm-6">
				<div class="overflow-hidden">
					<img class="img-responsive" src="<?=$this->imageLink('news/3raedicion.jpg')?>" alt="" />
				</div>
				<a target="_blank" class="btn-more hover-effect" href="http://lareferencia.redclara.net/rfr/noticias/lar-presenta-3era-edicion-especial-los-dos-anos-de-la-declaracion-de-buenos-aires">+ <?=$this->transEsc("read more")?></a>
			</div>
			<div class="caption col-md-12 col-sm-6">
				<h3>
					<a target="_blank" class="hover-effect" href="http://lareferencia.redclara.net/rfr/noticias/lar-presenta-3era-edicion-especial-los-dos-anos-de-la-declaracion-de-buenos-aires">LAR presenta 3era Edición Especial: A los dos años de la Declaración de Buenos Aires</a>
				</h3>
				<p>El proyecto LA Referencia se complace en presentar la 3era Edición Especial ...</p>
			</div>
		</div>
	</div>
</div>