<div class="headline">
		<h2>Noticias recientes</h2>
</div>
<div class="row margin-bottom-20">
	<div class="col-md-4 col-sm-12">
		<div class="thumbnails thumbnail-style thumbnail-kenburn">
			<div class="thumbnail-img col-md-12 col-sm-6">
				<div class="overflow-hidden">
					<img class="img-responsive" src="<?=$this->imageLink('news/intelligo.jpg')?>" alt="" />
				</div>
				<a target="_blank" class="btn-more hover-effect" href="http://lareferencia.redclara.net/rfr/noticias/llego-la-web-semantica-la-referencia">+ <?=$this->transEsc("read more")?></a>
			</div>
			<div class="caption col-md-12 col-sm-6">
				<h3>
					<a target="_blank" class="hover-effect" href="http://lareferencia.redclara.net/rfr/noticias/llego-la-web-semantica-la-referencia">Llegó la web semántica a LA Referencia</a>
				</h3>
				<p>LA Referencia ya se encuentra integrada a Intelligo, un explorador de grandes volúmenes de documentos de repositorios iberoamericanos</p>
			</div>
		</div>
	</div>
	<div class="col-md-4 col-sm-12">
		<div class="thumbnails thumbnail-style thumbnail-kenburn ">
			<div class="thumbnail-img col-md-12 col-sm-6">
				<div class="overflow-hidden">
					<img class="img-responsive" src="<?=$this->imageLink('news/alicia.jpg')?>" alt=""/>
				</div>
				<a target="_blank" class="btn-more hover-effect" href="http://lareferencia.redclara.net/rfr/noticias/peru-lanza-nueva-version-de-nodo-nacional">+ <?=$this->transEsc("read more")?></a>
			</div>
			<div class="caption col-md-12 col-sm-6">
				<h3>
					<a target="_blank" class="hover-effect" href="http://lareferencia.redclara.net/rfr/noticias/peru-lanza-nueva-version-de-nodo-nacional">Perú lanza nueva versión de nodo
						nacional</a>
				</h3>
				<p>Perú anunció el lanzamiento de la versión actualizada del nodo
					nacional peruano ALICIA en el cual se centraliza la producción.</p>
			</div>
		</div>
	</div>
	<div class="col-md-4 col-sm-12">
		<div class="thumbnails thumbnail-style thumbnail-kenburn ">
			<div class="thumbnail-img col-md-12 col-sm-6">
				<div class="overflow-hidden">
					<img class="img-responsive" src="<?=$this->imageLink('news/bandera.jpg')?>" alt="" />
				</div>
				<a target="_blank" class="btn-more hover-effect" href="http://lareferencia.redclara.net/rfr/noticias/argentina-apuntando-una-nueva-cultura-abierta-y-compartida">+ <?=$this->transEsc("read more")?></a>
			</div>
			<div class="caption col-md-12 col-sm-6">
				<h3>
					<a target="_blank" class="hover-effect" href="http://lareferencia.redclara.net/rfr/noticias/argentina-apuntando-una-nueva-cultura-abierta-y-compartida">Argentina: apuntando a una nueva cultura abierta y compartida</a>
				</h3>
				<p>A nueve meses de haber elevado una legislación nacional sobre repositorios digitales institucionales...</p>
			</div>
		</div>
	</div>
</div>