<div class="headline">
		<h2>Noticias destacadas</h2>
</div>
<div class="row margin-bottom-20">
	<div class="col-md-4 col-sm-12">
		<div class="thumbnails thumbnail-style thumbnail-kenburn">
			<div class="thumbnail-img col-md-12 col-sm-6">
				<div class="overflow-hidden">
					<img class="img-responsive" src="<?=$this->imageLink('news/reunionrio.jpg')?>" alt="" />
				</div>
				<a target="_blank" class="btn-more hover-effect" href="http://lareferencia.redclara.net/rfr/noticias/tras-reunion-en-rio-la-referencia-openaire-y-coar-reafirman-su-apoyo-una-vision-compartida-">+ <?=$this->transEsc("read more")?></a>
			</div>
			<div class="caption col-md-12 col-sm-6">
				<p><b>
					<a style="color:gray;" target="_blank" class="hover-effect" href="http://lareferencia.redclara.net/rfr/noticias/tras-reunion-en-rio-la-referencia-openaire-y-coar-reafirman-su-apoyo-una-vision-compartida-">LA Referencia, OpenAIRE y COAR reafirman su apoyo a una visión compartida de una red global de repositorios</a>
				</b></p>
				<p></p>
			</div>
		</div>
	</div>
	<div class="col-md-4 col-sm-12">
		<div class="thumbnails thumbnail-style thumbnail-kenburn ">
			<div class="thumbnail-img col-md-12 col-sm-6">
				<div class="overflow-hidden">
					<img class="img-responsive" src="<?=$this->imageLink('news/directrices.jpg')?>" alt=""/>
				</div>
				<a target="_blank" class="btn-more hover-effect" href="http://lareferencia.redclara.net/rfr/noticias/actualizacion-de-metadatos-y-politicas-de-cosecha-interoperables-para-los-nodos-nacionales">+ <?=$this->transEsc("read more")?></a>
			</div>
			<div class="caption col-md-12 col-sm-6">
				<h3>
					<a target="_blank" class="hover-effect" href="http://lareferencia.redclara.net/rfr/noticias/actualizacion-de-metadatos-y-politicas-de-cosecha-interoperables-para-los-nodos-nacionales">Actualización de Metadatos y Políticas de Cosecha</a>
				</h3>
				<p>Actualización de Metadatos y Políticas de Cosecha Interoperables para los Nodos Nacionales</p>
			</div>
		</div>
	</div>
	<div class="col-md-4 col-sm-12">
		<div class="thumbnails thumbnail-style thumbnail-kenburn ">
			<div class="thumbnail-img col-md-12 col-sm-6">
				<div class="overflow-hidden">
					<img class="img-responsive" src="<?=$this->imageLink('news/patriciamunozconicyt.jpg')?>" alt="" />
				</div>
				<a target="_blank" class="btn-more hover-effect" href="http://lareferencia.redclara.net/rfr/noticias/presidenta-de-la-referencia-es-elegida-en-consejo-directivo">+ <?=$this->transEsc("read more")?></a>
			</div>
			<div class="caption col-md-12 col-sm-6">
				<h3>
					<a target="_blank" class="hover-effect" href="http://lareferencia.redclara.net/rfr/noticias/presidenta-de-la-referencia-es-elegida-en-consejo-directivo">Presidenta de LA Referencia es elegida en Consejo Directivo</a>
				</h3>
				<p>En la reunión anual del Consejo Directivo de LA Referencia, en San Luis de Potosí, realizada entre el 2 y 4 de septiembre, fue elegida Patricia Muñoz Palma como Presidenta de LA Referencia por un período de dos años ...</p>
			</div>
		</div>
	</div>
</div>