<div class="headline">
		<h2>Featured news</h2>
</div>
<div class="row margin-bottom-20">
	<div class="col-md-4 col-sm-12">
		<div class="thumbnails thumbnail-style thumbnail-kenburn">
			<div class="thumbnail-img col-md-12 col-sm-6">
				<div class="overflow-hidden">
					<img class="img-responsive" src="<?=$this->imageLink('news/reunionrio.jpg')?>" alt="" />
				</div>
				<a target="_blank" class="btn-more hover-effect" href="http://lareferencia.redclara.net/rfr/noticias/la-referencia-openaire-and-coar-reaffirm-their-commitment-shared-vision-global-network-repo">+ <?=$this->transEsc("read more")?></a>
			</div>
			<div class="caption col-md-12 col-sm-6">
				<p><b>
					<a style="color:gray;" target="_blank" class="hover-effect" href="http://lareferencia.redclara.net/rfr/noticias/la-referencia-openaire-and-coar-reaffirm-their-commitment-shared-vision-global-network-repo">LA Referencia, OpenAIRE and COAR reaffirm their commitment to a shared vision of a global network of repositories</a>
				</b></p>
				<p></p>
			</div>
		</div>
	</div>
		<div class="col-md-4 col-sm-12">
		<div class="thumbnails thumbnail-style thumbnail-kenburn ">
			<div class="thumbnail-img col-md-12 col-sm-6">
				<div class="overflow-hidden">
					<img class="img-responsive" src="<?=$this->imageLink('news/directrices.jpg')?>" alt=""/>
				</div>
				<a target="_blank" class="btn-more hover-effect" href="http://lareferencia.redclara.net/rfr/noticias/interoperable-metadata-and-harvest-policies-national-nodes">+ <?=$this->transEsc("read more")?></a>
			</div>
			<div class="caption col-md-12 col-sm-6">
				<h3>
					<a target="_blank" class="hover-effect" href="http://lareferencia.redclara.net/rfr/noticias/interoperable-metadata-and-harvest-policies-national-nodes">Interoperable Metadata and Harvest Policies</a>
				</h3>
				<p>Interoperable Metadata and Harvest Policies for National Nodes</p>
			</div>
		</div>
	</div>
	<div class="col-md-4 col-sm-12">
		<div class="thumbnails thumbnail-style thumbnail-kenburn ">
			<div class="thumbnail-img col-md-12 col-sm-6">
				<div class="overflow-hidden">
					<img class="img-responsive" src="<?=$this->imageLink('news/3raedicion.jpg')?>" alt="" />
				</div>
				<a target="_blank" class="btn-more hover-effect" href="http://lareferencia.redclara.net/rfr/noticias/lar-presenta-3era-edicion-especial-los-dos-anos-de-la-declaracion-de-buenos-aires">+ <?=$this->transEsc("read more")?></a>
			</div>
			<div class="caption col-md-12 col-sm-6">
				<h3>
					<a target="_blank" class="hover-effect" href="http://lareferencia.redclara.net/rfr/noticias/lar-presenta-3era-edicion-especial-los-dos-anos-de-la-declaracion-de-buenos-aires">A los dos años de la Declaración de Buenos Aires</a>
				</h3>
				<p>El proyecto LA Referencia se complace en presentar la 3era Edición Especial ...</p>
			</div>
		</div>
	</div>
</div>