<div class="headline">
		<h2>Noticinias</h2>
</div>
<div class="row margin-bottom-20">
	<div class="col-md-4 col-sm-12">
		<div class="thumbnails thumbnail-style thumbnail-kenburn">
			<div class="thumbnail-img col-md-12 col-sm-6">
				<div class="overflow-hidden">
					<img class="img-responsive" src="<?=$this->imageLink('news/intelligo.jpg')?>" alt="" />
				</div>
				<a class="btn-more hover-effect" href="#">+ <?=$this->transEsc("read more")?></a>
			</div>
			<div class="caption col-md-12 col-sm-6">
				<h3>
					<a class="hover-effect" href="#">The Semantic Web Reached LA
						referencia</a>
				</h3>
				<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus,
					justo sit amet risus etiam porta sem.</p>
			</div>
		</div>
	</div>
	<div class="col-md-4 col-sm-12">
		<div class="thumbnails thumbnail-style thumbnail-kenburn ">
			<div class="thumbnail-img col-md-12 col-sm-6">
				<div class="overflow-hidden">
					<img class="img-responsive" src="<?=$this->imageLink('news/alicia.jpg')?>" alt=""/>
				</div>
				<a class="btn-more hover-effect" href="#">+ <?=$this->transEsc("read more")?></a>
			</div>
			<div class="caption col-md-12 col-sm-6">
				<h3>
					<a class="hover-effect" href="#">Perú lanza nueva versión de nodo
						nacional</a>
				</h3>
				<p>Perú anunció el lanzamiento de la versión actualizada del nodo
					nacional peruano ALICIA en el cual se centraliza la producción.</p>
			</div>
		</div>
	</div>
	<div class="col-md-4 col-sm-12">
		<div class="thumbnails thumbnail-style thumbnail-kenburn ">
			<div class="thumbnail-img col-md-12 col-sm-6">
				<div class="overflow-hidden">
					<img class="img-responsive" src="<?=$this->imageLink('news/bandera.jpg')?>" alt="" />
				</div>
				<a class="btn-more hover-effect" href="#">+ <?=$this->transEsc("read more")?></a>
			</div>
			<div class="caption col-md-12 col-sm-6">
				<h3>
					<a class="hover-effect" href="#">Argentina: apuntando a una nueva cultura abierta y compartida</a>
				</h3>
				<p>A nueve meses de haber elevado una legislación nacional sobre repositorios digitales institucionales...</p>
			</div>
		</div>
	</div>
</div>