<div class="row">
	<div id="wht-bwsr" class="col-md-8">
		<h3>Descripcion del servicio english</h3>
		<p>
			Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus etiam sem... <br/><a target="_blank" href="">read more</a> 
		</p>
	</div>
	<div id="explr-cat" class="col-md-4 btn-resources">
		<a target="_blank" href="http://www.lareferencia.info/intelligo/" class="btn-u">
			Explorar</a>
			</div>
</div>