<?
    // Set page title.
    $this->headTitle($this->translate('Statistics'));
    
    $this->headLink()->appendStylesheet('vendor/morris.css');
    $this->headLink()->appendStylesheet('vendor/dataTables.bootstrap.css');
    $this->headLink()->appendStylesheet('vendor/font-awesome.min.css');
    

    $this->headScript()->appendFile('vendor/morris/raphael.min.js');
    $this->headScript()->appendFile('vendor/morris/morris.min.js');

    $this->headScript()->appendFile('vendor/dataTables/jquery.dataTables.js');
    $this->headScript()->appendFile('vendor/dataTables/dataTables.bootstrap.js');    
?>



<div class="<?=$this->layoutClass('mainbody')?>">
  <!--h2><?=$this->transEsc('Statistics')?></h2-->


	
   <h2>Cantidad de documentos por tipo de documento</h2>

   <div class="row"><br/><br/></div>
   
   <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title"><i class="fa fa-bar-chart-o fa-fw"></i> Total Colección</h3>
                            </div>
                        <div class="panel-body">
                            <div id="main-donut-chart"></div>
			   				<div class="row"><br/><br/></div>
         		    		<div class="table-responsive">
                                <table  class="table table-striped table-bordered table-hover" id="main-datatable">
                                    <thead/>
                                    <tbody/>
                                </table>
                            </div>
			    			<div class="row"><br/><br/></div>
			    			
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-8 -->
            </div>
            <!-- /.row -->
            
            
            <div class="row">
            
            <? $dataByNetwork = $this->data; ?>
			<? foreach ( $dataByNetwork["pivots"] as $network => $data): ?>
			    			
            
                <div class="col-lg-3">
               		<div class="panel panel-default">
                    	<div class="panel-heading">
                              <h3 class="panel-title"><i class="fa fa-bar-chart-o fa-fw"></i> <?=$network?></h3>
                                
                         </div>
                         <div class="panel-body">
			    				<div id="<?=$network?>-donut-chart"></div>
                                <div class="text-right">
                            	<a href="#">Ver registros <i class="fa fa-arrow-circle-right"></i></a>
                            </div>
                         </div>
                         <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->                  
             	</div>
                <!-- /.col-lg-4 -->
                
             <? endforeach; ?>
                
             </div>
             <!-- /.row -->
             
             
                    
            
     
</div>


<script type="text/javascript">

var rawJson =  <?=json_encode($this->data) ?>;
var data = rawJson["fields"][<?=json_encode($this->field) ?>].values;
var sources = {};

Morris.Donut({
    element: 'main-donut-chart',
    data: data,
    resize: true
});

var columns = [];
columns.push({ 'data':'label', 'title':'Tipo de documento' });
columns.push({ 'data':'value', 'title':'Cantidad de registros' });

$('#main-datatable').dataTable( {
    data: data,
    columns: columns,
    bFilter: false, 
    bInfo: false,
    bPaginate: false
} );   

$.each( rawJson["pivots"], function( network, pivot ) {

	Morris.Donut({
	    element: network + '-donut-chart',
	    data: pivot.values,
	    resize: true
	});	
});

</script>

<div class="<?=$this->layoutClass('sidebar')?>">
  <?=$this->render("lareferencia/menu.phtml")?>
</div>
