
<div class="row"><br/></div>


<ul class="list-group">
  <a href="<?=$this->url('home')?>Statistics/Count?field=format" class="list-group-item<?=strtolower($this->field) == "format" ? ' active' : ''?>"><?=$this->transEsc('format_fieldname')?></a>
  <a href="<?=$this->url('home')?>Statistics/Count?field=language" class="list-group-item<?=strtolower($this->field) == "language" ? ' active' : ''?>"><?=$this->transEsc('language_fieldname')?></a>
  <a href="<?=$this->url('home')?>Statistics/Count?field=eu_rights" class="list-group-item<?=strtolower($this->field) == "eu_rights" ? ' active' : ''?>"><?=$this->transEsc('eu_rights_fieldname')?></a>
  <a href="<?=$this->url('home')?>Statistics/Count?field=publishDate&limit=20" class="list-group-item<?=strtolower($this->publishDate) == "count" ? ' active' : ''?>"><?=$this->transEsc('publishDate_fieldname')?> (top 20)</a>
  
  
  <a href="Clicks" class="list-group-item<?=strtolower($this->layout()->templateName) == "clicks" ? ' active' : ''?>"><?=$this->transEsc('Clicks')?></a>
  <a href="Networks" class="list-group-item<?=strtolower($this->layout()->templateName) == "networks" ? ' active' : ''?>"><?=$this->transEsc('Networks')?></a>
</ul>
