<ul class="list-group">
  <a href="Count" class="list-group-item<?=strtolower($this->layout()->templateName) == "count" ? ' active' : ''?>"><?=$this->transEsc('Document Type')?></a>
  <a href="Clicks" class="list-group-item<?=strtolower($this->layout()->templateName) == "clicks" ? ' active' : ''?>"><?=$this->transEsc('Clicks')?></a>
  <a href="Networks" class="list-group-item<?=strtolower($this->layout()->templateName) == "networks" ? ' active' : ''?>"><?=$this->transEsc('Networks')?></a>
</ul>
